// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_queue

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func QueueResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"amqp": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"queue_name": schema.StringAttribute{
						Computed:            true,
						Description:         "Name of the Ably queue.",
						MarkdownDescription: "Name of the Ably queue.",
					},
					"uri": schema.StringAttribute{
						Computed:            true,
						Description:         "URI for the AMQP queue interface.",
						MarkdownDescription: "URI for the AMQP queue interface.",
					},
				},
				CustomType: AmqpType{
					ObjectType: types.ObjectType{
						AttrTypes: AmqpValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"app_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The Ably application ID.",
				MarkdownDescription: "The Ably application ID.",
			},
			"deadletter": schema.BoolAttribute{
				Computed:            true,
				Description:         "A boolean that indicates whether this is a dead letter queue or not.",
				MarkdownDescription: "A boolean that indicates whether this is a dead letter queue or not.",
			},
			"deadletter_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the dead letter queue.",
				MarkdownDescription: "The ID of the dead letter queue.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the Ably queue",
				MarkdownDescription: "The ID of the Ably queue",
			},
			"max_length": schema.Int64Attribute{
				Required:            true,
				Description:         "Message limit in number of messages.",
				MarkdownDescription: "Message limit in number of messages.",
			},
			"messages": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"ready": schema.Int64Attribute{
						Computed:            true,
						Description:         "The number of ready messages in the queue.",
						MarkdownDescription: "The number of ready messages in the queue.",
					},
					"total": schema.Int64Attribute{
						Computed:            true,
						Description:         "The total number of messages in the queue.",
						MarkdownDescription: "The total number of messages in the queue.",
					},
					"unacknowledged": schema.Int64Attribute{
						Computed:            true,
						Description:         "The number of unacknowledged messages in the queue.",
						MarkdownDescription: "The number of unacknowledged messages in the queue.",
					},
				},
				CustomType: MessagesType{
					ObjectType: types.ObjectType{
						AttrTypes: MessagesValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Details of messages in the queue.",
				MarkdownDescription: "Details of messages in the queue.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "A friendly name for your queue.",
				MarkdownDescription: "A friendly name for your queue.",
			},
			"parent_app_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The application ID.",
				MarkdownDescription: "The application ID.",
			},
			"region": schema.StringAttribute{
				Required:            true,
				Description:         "The data center region. US East (Virginia) or EU West (Ireland). Values are `us-east-1-a` or `eu-west-1-a`.",
				MarkdownDescription: "The data center region. US East (Virginia) or EU West (Ireland). Values are `us-east-1-a` or `eu-west-1-a`.",
			},
			"state": schema.StringAttribute{
				Computed:            true,
				Description:         "The current state of the queue.",
				MarkdownDescription: "The current state of the queue.",
			},
			"stats": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"acknowledgement_rate": schema.NumberAttribute{
						Computed:            true,
						Description:         "The rate at which messages are acknowledged. Rate is messages per minute.",
						MarkdownDescription: "The rate at which messages are acknowledged. Rate is messages per minute.",
					},
					"delivery_rate": schema.NumberAttribute{
						Computed:            true,
						Description:         "The rate at which messages are delivered from the queue. Rate is messages per minute.",
						MarkdownDescription: "The rate at which messages are delivered from the queue. Rate is messages per minute.",
					},
					"publish_rate": schema.NumberAttribute{
						Computed:            true,
						Description:         "The rate at which messages are published to the queue. Rate is messages per minute.",
						MarkdownDescription: "The rate at which messages are published to the queue. Rate is messages per minute.",
					},
				},
				CustomType: StatsType{
					ObjectType: types.ObjectType{
						AttrTypes: StatsValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"stomp": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"destination": schema.StringAttribute{
						Computed:            true,
						Description:         "Destination queue.",
						MarkdownDescription: "Destination queue.",
					},
					"host": schema.StringAttribute{
						Computed:            true,
						Description:         "The host type for the queue.",
						MarkdownDescription: "The host type for the queue.",
					},
					"uri": schema.StringAttribute{
						Computed:            true,
						Description:         "URI for the STOMP queue interface.",
						MarkdownDescription: "URI for the STOMP queue interface.",
					},
				},
				CustomType: StompType{
					ObjectType: types.ObjectType{
						AttrTypes: StompValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"ttl": schema.Int64Attribute{
				Required:            true,
				Description:         "TTL in minutes.",
				MarkdownDescription: "TTL in minutes.",
			},
		},
	}
}

type QueueModel struct {
	Amqp         AmqpValue     `tfsdk:"amqp"`
	AppId        types.String  `tfsdk:"app_id"`
	Deadletter   types.Bool    `tfsdk:"deadletter"`
	DeadletterId types.String  `tfsdk:"deadletter_id"`
	Id           types.String  `tfsdk:"id"`
	MaxLength    types.Int64   `tfsdk:"max_length"`
	Messages     MessagesValue `tfsdk:"messages"`
	Name         types.String  `tfsdk:"name"`
	ParentAppId  types.String  `tfsdk:"parent_app_id"`
	Region       types.String  `tfsdk:"region"`
	State        types.String  `tfsdk:"state"`
	Stats        StatsValue    `tfsdk:"stats"`
	Stomp        StompValue    `tfsdk:"stomp"`
	Ttl          types.Int64   `tfsdk:"ttl"`
}

var _ basetypes.ObjectTypable = AmqpType{}

type AmqpType struct {
	basetypes.ObjectType
}

func (t AmqpType) Equal(o attr.Type) bool {
	other, ok := o.(AmqpType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AmqpType) String() string {
	return "AmqpType"
}

func (t AmqpType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	queueNameAttribute, ok := attributes["queue_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`queue_name is missing from object`)

		return nil, diags
	}

	queueNameVal, ok := queueNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`queue_name expected to be basetypes.StringValue, was: %T`, queueNameAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return nil, diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AmqpValue{
		QueueName: queueNameVal,
		Uri:       uriVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewAmqpValueNull() AmqpValue {
	return AmqpValue{
		state: attr.ValueStateNull,
	}
}

func NewAmqpValueUnknown() AmqpValue {
	return AmqpValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAmqpValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AmqpValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AmqpValue Attribute Value",
				"While creating a AmqpValue value, a missing attribute value was detected. "+
					"A AmqpValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AmqpValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AmqpValue Attribute Type",
				"While creating a AmqpValue value, an invalid attribute value was detected. "+
					"A AmqpValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AmqpValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AmqpValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AmqpValue Attribute Value",
				"While creating a AmqpValue value, an extra attribute value was detected. "+
					"A AmqpValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AmqpValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAmqpValueUnknown(), diags
	}

	queueNameAttribute, ok := attributes["queue_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`queue_name is missing from object`)

		return NewAmqpValueUnknown(), diags
	}

	queueNameVal, ok := queueNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`queue_name expected to be basetypes.StringValue, was: %T`, queueNameAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return NewAmqpValueUnknown(), diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return NewAmqpValueUnknown(), diags
	}

	return AmqpValue{
		QueueName: queueNameVal,
		Uri:       uriVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewAmqpValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AmqpValue {
	object, diags := NewAmqpValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAmqpValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AmqpType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAmqpValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAmqpValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAmqpValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAmqpValueMust(AmqpValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AmqpType) ValueType(ctx context.Context) attr.Value {
	return AmqpValue{}
}

var _ basetypes.ObjectValuable = AmqpValue{}

type AmqpValue struct {
	QueueName basetypes.StringValue `tfsdk:"queue_name"`
	Uri       basetypes.StringValue `tfsdk:"uri"`
	state     attr.ValueState
}

func (v AmqpValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["queue_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["uri"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.QueueName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["queue_name"] = val

		val, err = v.Uri.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["uri"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AmqpValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AmqpValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AmqpValue) String() string {
	return "AmqpValue"
}

func (v AmqpValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"queue_name": basetypes.StringType{},
		"uri":        basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"queue_name": v.QueueName,
			"uri":        v.Uri,
		})

	return objVal, diags
}

func (v AmqpValue) Equal(o attr.Value) bool {
	other, ok := o.(AmqpValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.QueueName.Equal(other.QueueName) {
		return false
	}

	if !v.Uri.Equal(other.Uri) {
		return false
	}

	return true
}

func (v AmqpValue) Type(ctx context.Context) attr.Type {
	return AmqpType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AmqpValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"queue_name": basetypes.StringType{},
		"uri":        basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = MessagesType{}

type MessagesType struct {
	basetypes.ObjectType
}

func (t MessagesType) Equal(o attr.Type) bool {
	other, ok := o.(MessagesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MessagesType) String() string {
	return "MessagesType"
}

func (t MessagesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	readyAttribute, ok := attributes["ready"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ready is missing from object`)

		return nil, diags
	}

	readyVal, ok := readyAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ready expected to be basetypes.Int64Value, was: %T`, readyAttribute))
	}

	totalAttribute, ok := attributes["total"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total is missing from object`)

		return nil, diags
	}

	totalVal, ok := totalAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total expected to be basetypes.Int64Value, was: %T`, totalAttribute))
	}

	unacknowledgedAttribute, ok := attributes["unacknowledged"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`unacknowledged is missing from object`)

		return nil, diags
	}

	unacknowledgedVal, ok := unacknowledgedAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`unacknowledged expected to be basetypes.Int64Value, was: %T`, unacknowledgedAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return MessagesValue{
		Ready:          readyVal,
		Total:          totalVal,
		Unacknowledged: unacknowledgedVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewMessagesValueNull() MessagesValue {
	return MessagesValue{
		state: attr.ValueStateNull,
	}
}

func NewMessagesValueUnknown() MessagesValue {
	return MessagesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewMessagesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MessagesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MessagesValue Attribute Value",
				"While creating a MessagesValue value, a missing attribute value was detected. "+
					"A MessagesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MessagesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MessagesValue Attribute Type",
				"While creating a MessagesValue value, an invalid attribute value was detected. "+
					"A MessagesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MessagesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MessagesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MessagesValue Attribute Value",
				"While creating a MessagesValue value, an extra attribute value was detected. "+
					"A MessagesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MessagesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewMessagesValueUnknown(), diags
	}

	readyAttribute, ok := attributes["ready"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ready is missing from object`)

		return NewMessagesValueUnknown(), diags
	}

	readyVal, ok := readyAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ready expected to be basetypes.Int64Value, was: %T`, readyAttribute))
	}

	totalAttribute, ok := attributes["total"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total is missing from object`)

		return NewMessagesValueUnknown(), diags
	}

	totalVal, ok := totalAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total expected to be basetypes.Int64Value, was: %T`, totalAttribute))
	}

	unacknowledgedAttribute, ok := attributes["unacknowledged"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`unacknowledged is missing from object`)

		return NewMessagesValueUnknown(), diags
	}

	unacknowledgedVal, ok := unacknowledgedAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`unacknowledged expected to be basetypes.Int64Value, was: %T`, unacknowledgedAttribute))
	}

	if diags.HasError() {
		return NewMessagesValueUnknown(), diags
	}

	return MessagesValue{
		Ready:          readyVal,
		Total:          totalVal,
		Unacknowledged: unacknowledgedVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewMessagesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MessagesValue {
	object, diags := NewMessagesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewMessagesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MessagesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewMessagesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewMessagesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMessagesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewMessagesValueMust(MessagesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MessagesType) ValueType(ctx context.Context) attr.Value {
	return MessagesValue{}
}

var _ basetypes.ObjectValuable = MessagesValue{}

type MessagesValue struct {
	Ready          basetypes.Int64Value `tfsdk:"ready"`
	Total          basetypes.Int64Value `tfsdk:"total"`
	Unacknowledged basetypes.Int64Value `tfsdk:"unacknowledged"`
	state          attr.ValueState
}

func (v MessagesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["ready"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["total"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["unacknowledged"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Ready.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ready"] = val

		val, err = v.Total.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["total"] = val

		val, err = v.Unacknowledged.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["unacknowledged"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MessagesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MessagesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MessagesValue) String() string {
	return "MessagesValue"
}

func (v MessagesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"ready":          basetypes.Int64Type{},
		"total":          basetypes.Int64Type{},
		"unacknowledged": basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"ready":          v.Ready,
			"total":          v.Total,
			"unacknowledged": v.Unacknowledged,
		})

	return objVal, diags
}

func (v MessagesValue) Equal(o attr.Value) bool {
	other, ok := o.(MessagesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Ready.Equal(other.Ready) {
		return false
	}

	if !v.Total.Equal(other.Total) {
		return false
	}

	if !v.Unacknowledged.Equal(other.Unacknowledged) {
		return false
	}

	return true
}

func (v MessagesValue) Type(ctx context.Context) attr.Type {
	return MessagesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MessagesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"ready":          basetypes.Int64Type{},
		"total":          basetypes.Int64Type{},
		"unacknowledged": basetypes.Int64Type{},
	}
}

var _ basetypes.ObjectTypable = StatsType{}

type StatsType struct {
	basetypes.ObjectType
}

func (t StatsType) Equal(o attr.Type) bool {
	other, ok := o.(StatsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t StatsType) String() string {
	return "StatsType"
}

func (t StatsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	acknowledgementRateAttribute, ok := attributes["acknowledgement_rate"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`acknowledgement_rate is missing from object`)

		return nil, diags
	}

	acknowledgementRateVal, ok := acknowledgementRateAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`acknowledgement_rate expected to be basetypes.NumberValue, was: %T`, acknowledgementRateAttribute))
	}

	deliveryRateAttribute, ok := attributes["delivery_rate"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`delivery_rate is missing from object`)

		return nil, diags
	}

	deliveryRateVal, ok := deliveryRateAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`delivery_rate expected to be basetypes.NumberValue, was: %T`, deliveryRateAttribute))
	}

	publishRateAttribute, ok := attributes["publish_rate"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`publish_rate is missing from object`)

		return nil, diags
	}

	publishRateVal, ok := publishRateAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`publish_rate expected to be basetypes.NumberValue, was: %T`, publishRateAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return StatsValue{
		AcknowledgementRate: acknowledgementRateVal,
		DeliveryRate:        deliveryRateVal,
		PublishRate:         publishRateVal,
		state:               attr.ValueStateKnown,
	}, diags
}

func NewStatsValueNull() StatsValue {
	return StatsValue{
		state: attr.ValueStateNull,
	}
}

func NewStatsValueUnknown() StatsValue {
	return StatsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewStatsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (StatsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing StatsValue Attribute Value",
				"While creating a StatsValue value, a missing attribute value was detected. "+
					"A StatsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("StatsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid StatsValue Attribute Type",
				"While creating a StatsValue value, an invalid attribute value was detected. "+
					"A StatsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("StatsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("StatsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra StatsValue Attribute Value",
				"While creating a StatsValue value, an extra attribute value was detected. "+
					"A StatsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra StatsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewStatsValueUnknown(), diags
	}

	acknowledgementRateAttribute, ok := attributes["acknowledgement_rate"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`acknowledgement_rate is missing from object`)

		return NewStatsValueUnknown(), diags
	}

	acknowledgementRateVal, ok := acknowledgementRateAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`acknowledgement_rate expected to be basetypes.NumberValue, was: %T`, acknowledgementRateAttribute))
	}

	deliveryRateAttribute, ok := attributes["delivery_rate"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`delivery_rate is missing from object`)

		return NewStatsValueUnknown(), diags
	}

	deliveryRateVal, ok := deliveryRateAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`delivery_rate expected to be basetypes.NumberValue, was: %T`, deliveryRateAttribute))
	}

	publishRateAttribute, ok := attributes["publish_rate"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`publish_rate is missing from object`)

		return NewStatsValueUnknown(), diags
	}

	publishRateVal, ok := publishRateAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`publish_rate expected to be basetypes.NumberValue, was: %T`, publishRateAttribute))
	}

	if diags.HasError() {
		return NewStatsValueUnknown(), diags
	}

	return StatsValue{
		AcknowledgementRate: acknowledgementRateVal,
		DeliveryRate:        deliveryRateVal,
		PublishRate:         publishRateVal,
		state:               attr.ValueStateKnown,
	}, diags
}

func NewStatsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) StatsValue {
	object, diags := NewStatsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewStatsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t StatsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewStatsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewStatsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewStatsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewStatsValueMust(StatsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t StatsType) ValueType(ctx context.Context) attr.Value {
	return StatsValue{}
}

var _ basetypes.ObjectValuable = StatsValue{}

type StatsValue struct {
	AcknowledgementRate basetypes.NumberValue `tfsdk:"acknowledgement_rate"`
	DeliveryRate        basetypes.NumberValue `tfsdk:"delivery_rate"`
	PublishRate         basetypes.NumberValue `tfsdk:"publish_rate"`
	state               attr.ValueState
}

func (v StatsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["acknowledgement_rate"] = basetypes.NumberType{}.TerraformType(ctx)
	attrTypes["delivery_rate"] = basetypes.NumberType{}.TerraformType(ctx)
	attrTypes["publish_rate"] = basetypes.NumberType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.AcknowledgementRate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["acknowledgement_rate"] = val

		val, err = v.DeliveryRate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["delivery_rate"] = val

		val, err = v.PublishRate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["publish_rate"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v StatsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v StatsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v StatsValue) String() string {
	return "StatsValue"
}

func (v StatsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"acknowledgement_rate": basetypes.NumberType{},
		"delivery_rate":        basetypes.NumberType{},
		"publish_rate":         basetypes.NumberType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"acknowledgement_rate": v.AcknowledgementRate,
			"delivery_rate":        v.DeliveryRate,
			"publish_rate":         v.PublishRate,
		})

	return objVal, diags
}

func (v StatsValue) Equal(o attr.Value) bool {
	other, ok := o.(StatsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AcknowledgementRate.Equal(other.AcknowledgementRate) {
		return false
	}

	if !v.DeliveryRate.Equal(other.DeliveryRate) {
		return false
	}

	if !v.PublishRate.Equal(other.PublishRate) {
		return false
	}

	return true
}

func (v StatsValue) Type(ctx context.Context) attr.Type {
	return StatsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v StatsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"acknowledgement_rate": basetypes.NumberType{},
		"delivery_rate":        basetypes.NumberType{},
		"publish_rate":         basetypes.NumberType{},
	}
}

var _ basetypes.ObjectTypable = StompType{}

type StompType struct {
	basetypes.ObjectType
}

func (t StompType) Equal(o attr.Type) bool {
	other, ok := o.(StompType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t StompType) String() string {
	return "StompType"
}

func (t StompType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	destinationAttribute, ok := attributes["destination"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`destination is missing from object`)

		return nil, diags
	}

	destinationVal, ok := destinationAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`destination expected to be basetypes.StringValue, was: %T`, destinationAttribute))
	}

	hostAttribute, ok := attributes["host"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`host is missing from object`)

		return nil, diags
	}

	hostVal, ok := hostAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`host expected to be basetypes.StringValue, was: %T`, hostAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return nil, diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return StompValue{
		Destination: destinationVal,
		Host:        hostVal,
		Uri:         uriVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewStompValueNull() StompValue {
	return StompValue{
		state: attr.ValueStateNull,
	}
}

func NewStompValueUnknown() StompValue {
	return StompValue{
		state: attr.ValueStateUnknown,
	}
}

func NewStompValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (StompValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing StompValue Attribute Value",
				"While creating a StompValue value, a missing attribute value was detected. "+
					"A StompValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("StompValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid StompValue Attribute Type",
				"While creating a StompValue value, an invalid attribute value was detected. "+
					"A StompValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("StompValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("StompValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra StompValue Attribute Value",
				"While creating a StompValue value, an extra attribute value was detected. "+
					"A StompValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra StompValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewStompValueUnknown(), diags
	}

	destinationAttribute, ok := attributes["destination"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`destination is missing from object`)

		return NewStompValueUnknown(), diags
	}

	destinationVal, ok := destinationAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`destination expected to be basetypes.StringValue, was: %T`, destinationAttribute))
	}

	hostAttribute, ok := attributes["host"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`host is missing from object`)

		return NewStompValueUnknown(), diags
	}

	hostVal, ok := hostAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`host expected to be basetypes.StringValue, was: %T`, hostAttribute))
	}

	uriAttribute, ok := attributes["uri"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`uri is missing from object`)

		return NewStompValueUnknown(), diags
	}

	uriVal, ok := uriAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`uri expected to be basetypes.StringValue, was: %T`, uriAttribute))
	}

	if diags.HasError() {
		return NewStompValueUnknown(), diags
	}

	return StompValue{
		Destination: destinationVal,
		Host:        hostVal,
		Uri:         uriVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewStompValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) StompValue {
	object, diags := NewStompValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewStompValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t StompType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewStompValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewStompValueUnknown(), nil
	}

	if in.IsNull() {
		return NewStompValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewStompValueMust(StompValue{}.AttributeTypes(ctx), attributes), nil
}

func (t StompType) ValueType(ctx context.Context) attr.Value {
	return StompValue{}
}

var _ basetypes.ObjectValuable = StompValue{}

type StompValue struct {
	Destination basetypes.StringValue `tfsdk:"destination"`
	Host        basetypes.StringValue `tfsdk:"host"`
	Uri         basetypes.StringValue `tfsdk:"uri"`
	state       attr.ValueState
}

func (v StompValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["destination"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["host"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["uri"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Destination.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["destination"] = val

		val, err = v.Host.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["host"] = val

		val, err = v.Uri.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["uri"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v StompValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v StompValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v StompValue) String() string {
	return "StompValue"
}

func (v StompValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"destination": basetypes.StringType{},
		"host":        basetypes.StringType{},
		"uri":         basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"destination": v.Destination,
			"host":        v.Host,
			"uri":         v.Uri,
		})

	return objVal, diags
}

func (v StompValue) Equal(o attr.Value) bool {
	other, ok := o.(StompValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Destination.Equal(other.Destination) {
		return false
	}

	if !v.Host.Equal(other.Host) {
		return false
	}

	if !v.Uri.Equal(other.Uri) {
		return false
	}

	return true
}

func (v StompValue) Type(ctx context.Context) attr.Type {
	return StompType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v StompValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"destination": basetypes.StringType{},
		"host":        basetypes.StringType{},
		"uri":         basetypes.StringType{},
	}
}
