// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_namespaces

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func NamespacesDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"app_id": schema.StringAttribute{
				Required:            true,
				Description:         "The application ID.",
				MarkdownDescription: "The application ID.",
			},
			"namespaces": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"app_id": schema.StringAttribute{
							Computed:            true,
							Description:         "The ID of the application the namespace belongs to.",
							MarkdownDescription: "The ID of the application the namespace belongs to.",
						},
						"authenticated": schema.BoolAttribute{
							Computed:            true,
							Description:         "If `true`, clients will not be permitted to use (including to attach, publish, or subscribe) any channels within this namespace unless they are identified, that is, authenticated using a client ID. See the documentation for <a href=\"https://ably.com/docs/auth/identified-clients\">identified clients</a> for more details.",
							MarkdownDescription: "If `true`, clients will not be permitted to use (including to attach, publish, or subscribe) any channels within this namespace unless they are identified, that is, authenticated using a client ID. See the documentation for <a href=\"https://ably.com/docs/auth/identified-clients\">identified clients</a> for more details.",
						},
						"batching_enabled": schema.BoolAttribute{
							Computed:            true,
							Description:         "If `true`, channels within this namespace will start batching inbound messages instead of sending them out immediately to subscribers.",
							MarkdownDescription: "If `true`, channels within this namespace will start batching inbound messages instead of sending them out immediately to subscribers.",
						},
						"batching_interval": schema.Int64Attribute{
							Computed:            true,
							Description:         "If `true`, the batching interval, configurable from 20ms to 1s, temporarily holds and aggregates incoming messages. These messages are then combined and delivered as a single batch once the interval elapses or a size limit is reached (before the interval elapses).",
							MarkdownDescription: "If `true`, the batching interval, configurable from 20ms to 1s, temporarily holds and aggregates incoming messages. These messages are then combined and delivered as a single batch once the interval elapses or a size limit is reached (before the interval elapses).",
						},
						"conflation_enabled": schema.BoolAttribute{
							Computed:            true,
							Description:         "If `true`, enables <a href=\"https://ably.com/docs/messages#conflation\">conflation</a> for channels within this namespace. Conflation will aggregate published messages for a set period of time and evaluate them against a conflation key. Only the most recent message that satisfies the key will be sent to subscribers at the end of the conflation interval.",
							MarkdownDescription: "If `true`, enables <a href=\"https://ably.com/docs/messages#conflation\">conflation</a> for channels within this namespace. Conflation will aggregate published messages for a set period of time and evaluate them against a conflation key. Only the most recent message that satisfies the key will be sent to subscribers at the end of the conflation interval.",
						},
						"conflation_interval": schema.Int64Attribute{
							Computed:            true,
							Description:         "The interval in milliseconds over which messages are held and evaluated for conflation.",
							MarkdownDescription: "The interval in milliseconds over which messages are held and evaluated for conflation.",
						},
						"conflation_key": schema.StringAttribute{
							Computed:            true,
							Description:         "The <a href=\"https://ably.com/docs/messages#routing\">key</a> used to determine which messages should be conflated.",
							MarkdownDescription: "The <a href=\"https://ably.com/docs/messages#routing\">key</a> used to determine which messages should be conflated.",
						},
						"created": schema.Int64Attribute{
							Computed:            true,
							Description:         "Unix timestamp representing the date and time of creation of the namespace.",
							MarkdownDescription: "Unix timestamp representing the date and time of creation of the namespace.",
						},
						"expose_timeserial": schema.BoolAttribute{
							Computed:            true,
							Description:         "If `true`, messages received on a channel will contain a unique `timeserial` that can be referenced by later messages for use with message interactions.",
							MarkdownDescription: "If `true`, messages received on a channel will contain a unique `timeserial` that can be referenced by later messages for use with message interactions.",
						},
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "The namespace or channel name that the channel rule will apply to. For example, if you specify `namespace` the namespace will be set to `namespace` and will match with channels `namespace:*` and `namespace`.",
							MarkdownDescription: "The namespace or channel name that the channel rule will apply to. For example, if you specify `namespace` the namespace will be set to `namespace` and will match with channels `namespace:*` and `namespace`.",
						},
						"modified": schema.Int64Attribute{
							Computed:            true,
							Description:         "Unix timestamp representing the date and time of last modification of the namespace.",
							MarkdownDescription: "Unix timestamp representing the date and time of last modification of the namespace.",
						},
						"mutable_messages": schema.BoolAttribute{
							Computed:            true,
							Description:         "If `true`, messages published on channels within this namespace can be updated or deleted after publishing. See the <a href=\"https://ably.com/docs/messages#update\">message interactions</a> documentation for more details.",
							MarkdownDescription: "If `true`, messages published on channels within this namespace can be updated or deleted after publishing. See the <a href=\"https://ably.com/docs/messages#update\">message interactions</a> documentation for more details.",
						},
						"persist_last": schema.BoolAttribute{
							Computed:            true,
							Description:         "If `true`, the last message published on a channel will be stored for 365 days. You can access the stored message only by using the channel rewind mechanism and attaching with rewind=1. Please note that for each message stored, an additional message is deducted from your monthly allocation.",
							MarkdownDescription: "If `true`, the last message published on a channel will be stored for 365 days. You can access the stored message only by using the channel rewind mechanism and attaching with rewind=1. Please note that for each message stored, an additional message is deducted from your monthly allocation.",
						},
						"persisted": schema.BoolAttribute{
							Computed:            true,
							Description:         "If `true`, all messages on a channel will be stored for 24 hours. You can access stored messages via the History API. Please note that for each message stored, an additional message is deducted from your monthly allocation.",
							MarkdownDescription: "If `true`, all messages on a channel will be stored for 24 hours. You can access stored messages via the History API. Please note that for each message stored, an additional message is deducted from your monthly allocation.",
						},
						"populate_channel_registry": schema.BoolAttribute{
							Computed:            true,
							Description:         "If `true`, channels within this namespace are included in the channel registry, enabling channel enumeration via the <a href=\"https://ably.com/docs/metadata-stats/metadata/subscribe#channel-lifecycle\">Channel Metadata API</a>.",
							MarkdownDescription: "If `true`, channels within this namespace are included in the channel registry, enabling channel enumeration via the <a href=\"https://ably.com/docs/metadata-stats/metadata/subscribe#channel-lifecycle\">Channel Metadata API</a>.",
						},
						"push_enabled": schema.BoolAttribute{
							Computed:            true,
							Description:         "If `true`, publishing messages with a push payload in the extras field is permitted and can trigger the delivery of a native push notification to registered devices for the channel.",
							MarkdownDescription: "If `true`, publishing messages with a push payload in the extras field is permitted and can trigger the delivery of a native push notification to registered devices for the channel.",
						},
						"tls_only": schema.BoolAttribute{
							Computed:            true,
							Description:         "If `true`, only clients that are connected using TLS will be permitted to subscribe to any channels within this namespace.",
							MarkdownDescription: "If `true`, only clients that are connected using TLS will be permitted to subscribe to any channels within this namespace.",
						},
					},
					CustomType: NamespacesType{
						ObjectType: types.ObjectType{
							AttrTypes: NamespacesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type NamespacesModel struct {
	AppId      types.String `tfsdk:"app_id"`
	Namespaces types.Set    `tfsdk:"namespaces"`
}

var _ basetypes.ObjectTypable = NamespacesType{}

type NamespacesType struct {
	basetypes.ObjectType
}

func (t NamespacesType) Equal(o attr.Type) bool {
	other, ok := o.(NamespacesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t NamespacesType) String() string {
	return "NamespacesType"
}

func (t NamespacesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	appIdAttribute, ok := attributes["app_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`app_id is missing from object`)

		return nil, diags
	}

	appIdVal, ok := appIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`app_id expected to be basetypes.StringValue, was: %T`, appIdAttribute))
	}

	authenticatedAttribute, ok := attributes["authenticated"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`authenticated is missing from object`)

		return nil, diags
	}

	authenticatedVal, ok := authenticatedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`authenticated expected to be basetypes.BoolValue, was: %T`, authenticatedAttribute))
	}

	batchingEnabledAttribute, ok := attributes["batching_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`batching_enabled is missing from object`)

		return nil, diags
	}

	batchingEnabledVal, ok := batchingEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`batching_enabled expected to be basetypes.BoolValue, was: %T`, batchingEnabledAttribute))
	}

	batchingIntervalAttribute, ok := attributes["batching_interval"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`batching_interval is missing from object`)

		return nil, diags
	}

	batchingIntervalVal, ok := batchingIntervalAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`batching_interval expected to be basetypes.Int64Value, was: %T`, batchingIntervalAttribute))
	}

	conflationEnabledAttribute, ok := attributes["conflation_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`conflation_enabled is missing from object`)

		return nil, diags
	}

	conflationEnabledVal, ok := conflationEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`conflation_enabled expected to be basetypes.BoolValue, was: %T`, conflationEnabledAttribute))
	}

	conflationIntervalAttribute, ok := attributes["conflation_interval"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`conflation_interval is missing from object`)

		return nil, diags
	}

	conflationIntervalVal, ok := conflationIntervalAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`conflation_interval expected to be basetypes.Int64Value, was: %T`, conflationIntervalAttribute))
	}

	conflationKeyAttribute, ok := attributes["conflation_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`conflation_key is missing from object`)

		return nil, diags
	}

	conflationKeyVal, ok := conflationKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`conflation_key expected to be basetypes.StringValue, was: %T`, conflationKeyAttribute))
	}

	createdAttribute, ok := attributes["created"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created is missing from object`)

		return nil, diags
	}

	createdVal, ok := createdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created expected to be basetypes.Int64Value, was: %T`, createdAttribute))
	}

	exposeTimeserialAttribute, ok := attributes["expose_timeserial"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`expose_timeserial is missing from object`)

		return nil, diags
	}

	exposeTimeserialVal, ok := exposeTimeserialAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`expose_timeserial expected to be basetypes.BoolValue, was: %T`, exposeTimeserialAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	modifiedAttribute, ok := attributes["modified"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`modified is missing from object`)

		return nil, diags
	}

	modifiedVal, ok := modifiedAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`modified expected to be basetypes.Int64Value, was: %T`, modifiedAttribute))
	}

	mutableMessagesAttribute, ok := attributes["mutable_messages"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`mutable_messages is missing from object`)

		return nil, diags
	}

	mutableMessagesVal, ok := mutableMessagesAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`mutable_messages expected to be basetypes.BoolValue, was: %T`, mutableMessagesAttribute))
	}

	persistLastAttribute, ok := attributes["persist_last"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`persist_last is missing from object`)

		return nil, diags
	}

	persistLastVal, ok := persistLastAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`persist_last expected to be basetypes.BoolValue, was: %T`, persistLastAttribute))
	}

	persistedAttribute, ok := attributes["persisted"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`persisted is missing from object`)

		return nil, diags
	}

	persistedVal, ok := persistedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`persisted expected to be basetypes.BoolValue, was: %T`, persistedAttribute))
	}

	populateChannelRegistryAttribute, ok := attributes["populate_channel_registry"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`populate_channel_registry is missing from object`)

		return nil, diags
	}

	populateChannelRegistryVal, ok := populateChannelRegistryAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`populate_channel_registry expected to be basetypes.BoolValue, was: %T`, populateChannelRegistryAttribute))
	}

	pushEnabledAttribute, ok := attributes["push_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`push_enabled is missing from object`)

		return nil, diags
	}

	pushEnabledVal, ok := pushEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`push_enabled expected to be basetypes.BoolValue, was: %T`, pushEnabledAttribute))
	}

	tlsOnlyAttribute, ok := attributes["tls_only"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tls_only is missing from object`)

		return nil, diags
	}

	tlsOnlyVal, ok := tlsOnlyAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tls_only expected to be basetypes.BoolValue, was: %T`, tlsOnlyAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return NamespacesValue{
		AppId:                   appIdVal,
		Authenticated:           authenticatedVal,
		BatchingEnabled:         batchingEnabledVal,
		BatchingInterval:        batchingIntervalVal,
		ConflationEnabled:       conflationEnabledVal,
		ConflationInterval:      conflationIntervalVal,
		ConflationKey:           conflationKeyVal,
		Created:                 createdVal,
		ExposeTimeserial:        exposeTimeserialVal,
		Id:                      idVal,
		Modified:                modifiedVal,
		MutableMessages:         mutableMessagesVal,
		PersistLast:             persistLastVal,
		Persisted:               persistedVal,
		PopulateChannelRegistry: populateChannelRegistryVal,
		PushEnabled:             pushEnabledVal,
		TlsOnly:                 tlsOnlyVal,
		state:                   attr.ValueStateKnown,
	}, diags
}

func NewNamespacesValueNull() NamespacesValue {
	return NamespacesValue{
		state: attr.ValueStateNull,
	}
}

func NewNamespacesValueUnknown() NamespacesValue {
	return NamespacesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewNamespacesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (NamespacesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing NamespacesValue Attribute Value",
				"While creating a NamespacesValue value, a missing attribute value was detected. "+
					"A NamespacesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NamespacesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid NamespacesValue Attribute Type",
				"While creating a NamespacesValue value, an invalid attribute value was detected. "+
					"A NamespacesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NamespacesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("NamespacesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra NamespacesValue Attribute Value",
				"While creating a NamespacesValue value, an extra attribute value was detected. "+
					"A NamespacesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra NamespacesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewNamespacesValueUnknown(), diags
	}

	appIdAttribute, ok := attributes["app_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`app_id is missing from object`)

		return NewNamespacesValueUnknown(), diags
	}

	appIdVal, ok := appIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`app_id expected to be basetypes.StringValue, was: %T`, appIdAttribute))
	}

	authenticatedAttribute, ok := attributes["authenticated"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`authenticated is missing from object`)

		return NewNamespacesValueUnknown(), diags
	}

	authenticatedVal, ok := authenticatedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`authenticated expected to be basetypes.BoolValue, was: %T`, authenticatedAttribute))
	}

	batchingEnabledAttribute, ok := attributes["batching_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`batching_enabled is missing from object`)

		return NewNamespacesValueUnknown(), diags
	}

	batchingEnabledVal, ok := batchingEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`batching_enabled expected to be basetypes.BoolValue, was: %T`, batchingEnabledAttribute))
	}

	batchingIntervalAttribute, ok := attributes["batching_interval"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`batching_interval is missing from object`)

		return NewNamespacesValueUnknown(), diags
	}

	batchingIntervalVal, ok := batchingIntervalAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`batching_interval expected to be basetypes.Int64Value, was: %T`, batchingIntervalAttribute))
	}

	conflationEnabledAttribute, ok := attributes["conflation_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`conflation_enabled is missing from object`)

		return NewNamespacesValueUnknown(), diags
	}

	conflationEnabledVal, ok := conflationEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`conflation_enabled expected to be basetypes.BoolValue, was: %T`, conflationEnabledAttribute))
	}

	conflationIntervalAttribute, ok := attributes["conflation_interval"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`conflation_interval is missing from object`)

		return NewNamespacesValueUnknown(), diags
	}

	conflationIntervalVal, ok := conflationIntervalAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`conflation_interval expected to be basetypes.Int64Value, was: %T`, conflationIntervalAttribute))
	}

	conflationKeyAttribute, ok := attributes["conflation_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`conflation_key is missing from object`)

		return NewNamespacesValueUnknown(), diags
	}

	conflationKeyVal, ok := conflationKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`conflation_key expected to be basetypes.StringValue, was: %T`, conflationKeyAttribute))
	}

	createdAttribute, ok := attributes["created"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created is missing from object`)

		return NewNamespacesValueUnknown(), diags
	}

	createdVal, ok := createdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created expected to be basetypes.Int64Value, was: %T`, createdAttribute))
	}

	exposeTimeserialAttribute, ok := attributes["expose_timeserial"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`expose_timeserial is missing from object`)

		return NewNamespacesValueUnknown(), diags
	}

	exposeTimeserialVal, ok := exposeTimeserialAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`expose_timeserial expected to be basetypes.BoolValue, was: %T`, exposeTimeserialAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewNamespacesValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	modifiedAttribute, ok := attributes["modified"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`modified is missing from object`)

		return NewNamespacesValueUnknown(), diags
	}

	modifiedVal, ok := modifiedAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`modified expected to be basetypes.Int64Value, was: %T`, modifiedAttribute))
	}

	mutableMessagesAttribute, ok := attributes["mutable_messages"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`mutable_messages is missing from object`)

		return NewNamespacesValueUnknown(), diags
	}

	mutableMessagesVal, ok := mutableMessagesAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`mutable_messages expected to be basetypes.BoolValue, was: %T`, mutableMessagesAttribute))
	}

	persistLastAttribute, ok := attributes["persist_last"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`persist_last is missing from object`)

		return NewNamespacesValueUnknown(), diags
	}

	persistLastVal, ok := persistLastAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`persist_last expected to be basetypes.BoolValue, was: %T`, persistLastAttribute))
	}

	persistedAttribute, ok := attributes["persisted"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`persisted is missing from object`)

		return NewNamespacesValueUnknown(), diags
	}

	persistedVal, ok := persistedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`persisted expected to be basetypes.BoolValue, was: %T`, persistedAttribute))
	}

	populateChannelRegistryAttribute, ok := attributes["populate_channel_registry"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`populate_channel_registry is missing from object`)

		return NewNamespacesValueUnknown(), diags
	}

	populateChannelRegistryVal, ok := populateChannelRegistryAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`populate_channel_registry expected to be basetypes.BoolValue, was: %T`, populateChannelRegistryAttribute))
	}

	pushEnabledAttribute, ok := attributes["push_enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`push_enabled is missing from object`)

		return NewNamespacesValueUnknown(), diags
	}

	pushEnabledVal, ok := pushEnabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`push_enabled expected to be basetypes.BoolValue, was: %T`, pushEnabledAttribute))
	}

	tlsOnlyAttribute, ok := attributes["tls_only"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tls_only is missing from object`)

		return NewNamespacesValueUnknown(), diags
	}

	tlsOnlyVal, ok := tlsOnlyAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tls_only expected to be basetypes.BoolValue, was: %T`, tlsOnlyAttribute))
	}

	if diags.HasError() {
		return NewNamespacesValueUnknown(), diags
	}

	return NamespacesValue{
		AppId:                   appIdVal,
		Authenticated:           authenticatedVal,
		BatchingEnabled:         batchingEnabledVal,
		BatchingInterval:        batchingIntervalVal,
		ConflationEnabled:       conflationEnabledVal,
		ConflationInterval:      conflationIntervalVal,
		ConflationKey:           conflationKeyVal,
		Created:                 createdVal,
		ExposeTimeserial:        exposeTimeserialVal,
		Id:                      idVal,
		Modified:                modifiedVal,
		MutableMessages:         mutableMessagesVal,
		PersistLast:             persistLastVal,
		Persisted:               persistedVal,
		PopulateChannelRegistry: populateChannelRegistryVal,
		PushEnabled:             pushEnabledVal,
		TlsOnly:                 tlsOnlyVal,
		state:                   attr.ValueStateKnown,
	}, diags
}

func NewNamespacesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) NamespacesValue {
	object, diags := NewNamespacesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewNamespacesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t NamespacesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewNamespacesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewNamespacesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewNamespacesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewNamespacesValueMust(NamespacesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t NamespacesType) ValueType(ctx context.Context) attr.Value {
	return NamespacesValue{}
}

var _ basetypes.ObjectValuable = NamespacesValue{}

type NamespacesValue struct {
	AppId                   basetypes.StringValue `tfsdk:"app_id"`
	Authenticated           basetypes.BoolValue   `tfsdk:"authenticated"`
	BatchingEnabled         basetypes.BoolValue   `tfsdk:"batching_enabled"`
	BatchingInterval        basetypes.Int64Value  `tfsdk:"batching_interval"`
	ConflationEnabled       basetypes.BoolValue   `tfsdk:"conflation_enabled"`
	ConflationInterval      basetypes.Int64Value  `tfsdk:"conflation_interval"`
	ConflationKey           basetypes.StringValue `tfsdk:"conflation_key"`
	Created                 basetypes.Int64Value  `tfsdk:"created"`
	ExposeTimeserial        basetypes.BoolValue   `tfsdk:"expose_timeserial"`
	Id                      basetypes.StringValue `tfsdk:"id"`
	Modified                basetypes.Int64Value  `tfsdk:"modified"`
	MutableMessages         basetypes.BoolValue   `tfsdk:"mutable_messages"`
	PersistLast             basetypes.BoolValue   `tfsdk:"persist_last"`
	Persisted               basetypes.BoolValue   `tfsdk:"persisted"`
	PopulateChannelRegistry basetypes.BoolValue   `tfsdk:"populate_channel_registry"`
	PushEnabled             basetypes.BoolValue   `tfsdk:"push_enabled"`
	TlsOnly                 basetypes.BoolValue   `tfsdk:"tls_only"`
	state                   attr.ValueState
}

func (v NamespacesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 17)

	var val tftypes.Value
	var err error

	attrTypes["app_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["authenticated"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["batching_enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["batching_interval"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["conflation_enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["conflation_interval"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["conflation_key"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["created"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["expose_timeserial"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["modified"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["mutable_messages"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["persist_last"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["persisted"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["populate_channel_registry"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["push_enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tls_only"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 17)

		val, err = v.AppId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["app_id"] = val

		val, err = v.Authenticated.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["authenticated"] = val

		val, err = v.BatchingEnabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["batching_enabled"] = val

		val, err = v.BatchingInterval.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["batching_interval"] = val

		val, err = v.ConflationEnabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["conflation_enabled"] = val

		val, err = v.ConflationInterval.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["conflation_interval"] = val

		val, err = v.ConflationKey.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["conflation_key"] = val

		val, err = v.Created.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created"] = val

		val, err = v.ExposeTimeserial.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["expose_timeserial"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Modified.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["modified"] = val

		val, err = v.MutableMessages.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["mutable_messages"] = val

		val, err = v.PersistLast.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["persist_last"] = val

		val, err = v.Persisted.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["persisted"] = val

		val, err = v.PopulateChannelRegistry.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["populate_channel_registry"] = val

		val, err = v.PushEnabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["push_enabled"] = val

		val, err = v.TlsOnly.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tls_only"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v NamespacesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v NamespacesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v NamespacesValue) String() string {
	return "NamespacesValue"
}

func (v NamespacesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"app_id":                    basetypes.StringType{},
		"authenticated":             basetypes.BoolType{},
		"batching_enabled":          basetypes.BoolType{},
		"batching_interval":         basetypes.Int64Type{},
		"conflation_enabled":        basetypes.BoolType{},
		"conflation_interval":       basetypes.Int64Type{},
		"conflation_key":            basetypes.StringType{},
		"created":                   basetypes.Int64Type{},
		"expose_timeserial":         basetypes.BoolType{},
		"id":                        basetypes.StringType{},
		"modified":                  basetypes.Int64Type{},
		"mutable_messages":          basetypes.BoolType{},
		"persist_last":              basetypes.BoolType{},
		"persisted":                 basetypes.BoolType{},
		"populate_channel_registry": basetypes.BoolType{},
		"push_enabled":              basetypes.BoolType{},
		"tls_only":                  basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"app_id":                    v.AppId,
			"authenticated":             v.Authenticated,
			"batching_enabled":          v.BatchingEnabled,
			"batching_interval":         v.BatchingInterval,
			"conflation_enabled":        v.ConflationEnabled,
			"conflation_interval":       v.ConflationInterval,
			"conflation_key":            v.ConflationKey,
			"created":                   v.Created,
			"expose_timeserial":         v.ExposeTimeserial,
			"id":                        v.Id,
			"modified":                  v.Modified,
			"mutable_messages":          v.MutableMessages,
			"persist_last":              v.PersistLast,
			"persisted":                 v.Persisted,
			"populate_channel_registry": v.PopulateChannelRegistry,
			"push_enabled":              v.PushEnabled,
			"tls_only":                  v.TlsOnly,
		})

	return objVal, diags
}

func (v NamespacesValue) Equal(o attr.Value) bool {
	other, ok := o.(NamespacesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AppId.Equal(other.AppId) {
		return false
	}

	if !v.Authenticated.Equal(other.Authenticated) {
		return false
	}

	if !v.BatchingEnabled.Equal(other.BatchingEnabled) {
		return false
	}

	if !v.BatchingInterval.Equal(other.BatchingInterval) {
		return false
	}

	if !v.ConflationEnabled.Equal(other.ConflationEnabled) {
		return false
	}

	if !v.ConflationInterval.Equal(other.ConflationInterval) {
		return false
	}

	if !v.ConflationKey.Equal(other.ConflationKey) {
		return false
	}

	if !v.Created.Equal(other.Created) {
		return false
	}

	if !v.ExposeTimeserial.Equal(other.ExposeTimeserial) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Modified.Equal(other.Modified) {
		return false
	}

	if !v.MutableMessages.Equal(other.MutableMessages) {
		return false
	}

	if !v.PersistLast.Equal(other.PersistLast) {
		return false
	}

	if !v.Persisted.Equal(other.Persisted) {
		return false
	}

	if !v.PopulateChannelRegistry.Equal(other.PopulateChannelRegistry) {
		return false
	}

	if !v.PushEnabled.Equal(other.PushEnabled) {
		return false
	}

	if !v.TlsOnly.Equal(other.TlsOnly) {
		return false
	}

	return true
}

func (v NamespacesValue) Type(ctx context.Context) attr.Type {
	return NamespacesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v NamespacesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"app_id":                    basetypes.StringType{},
		"authenticated":             basetypes.BoolType{},
		"batching_enabled":          basetypes.BoolType{},
		"batching_interval":         basetypes.Int64Type{},
		"conflation_enabled":        basetypes.BoolType{},
		"conflation_interval":       basetypes.Int64Type{},
		"conflation_key":            basetypes.StringType{},
		"created":                   basetypes.Int64Type{},
		"expose_timeserial":         basetypes.BoolType{},
		"id":                        basetypes.StringType{},
		"modified":                  basetypes.Int64Type{},
		"mutable_messages":          basetypes.BoolType{},
		"persist_last":              basetypes.BoolType{},
		"persisted":                 basetypes.BoolType{},
		"populate_channel_registry": basetypes.BoolType{},
		"push_enabled":              basetypes.BoolType{},
		"tls_only":                  basetypes.BoolType{},
	}
}
