version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    groups:
      terraform-plugin:
        patterns:
          - 'github.com/hashicorp/terraform-plugin*'
