// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_rule_before_publish_webhook

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func RuleBeforePublishWebhookResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"app_id": schema.StringAttribute{
				Required:            true,
				Description:         "The Ably application ID.",
				MarkdownDescription: "The Ably application ID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"before_publish_config": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"failed_action": schema.StringAttribute{
						Required:            true,
						Description:         "The action to take if the rule invocation fails. `REJECT` prevents the message from being published, `PUBLISH` allows it through.",
						MarkdownDescription: "The action to take if the rule invocation fails. `REJECT` prevents the message from being published, `PUBLISH` allows it through.",
						Validators: []validator.String{
							stringvalidator.OneOf("REJECT", "PUBLISH"),
						},
					},
					"max_retries": schema.Int64Attribute{
						Required:            true,
						Description:         "The maximum number of retry attempts.",
						MarkdownDescription: "The maximum number of retry attempts.",
					},
					"retry_timeout": schema.Int64Attribute{
						Required:            true,
						Description:         "The timeout in milliseconds for retrying the rule invocation.",
						MarkdownDescription: "The timeout in milliseconds for retrying the rule invocation.",
					},
					"too_many_requests_action": schema.StringAttribute{
						Required:            true,
						Description:         "The action to take if the rule invocation returns a rate limit response. `RETRY` will attempt the request again, `FAIL` will invoke the `failedAction`.",
						MarkdownDescription: "The action to take if the rule invocation returns a rate limit response. `RETRY` will attempt the request again, `FAIL` will invoke the `failedAction`.",
						Validators: []validator.String{
							stringvalidator.OneOf("RETRY", "FAIL"),
						},
					},
				},
				CustomType: BeforePublishConfigType{
					ObjectType: types.ObjectType{
						AttrTypes: BeforePublishConfigValue{}.AttributeTypes(ctx),
					},
				},
				Required:            true,
				Description:         "Configuration for before-publish behavior, including retry logic and failure handling.",
				MarkdownDescription: "Configuration for before-publish behavior, including retry logic and failure handling.",
			},
			"chat_room_filter": schema.StringAttribute{
				Optional:            true,
				Description:         "A regular expression that filters messages based on the chat room ID. Only messages matching this pattern will trigger the rule.",
				MarkdownDescription: "A regular expression that filters messages based on the chat room ID. Only messages matching this pattern will trigger the rule.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^/.*/$"), "must match the pattern ^/.*/$"),
					stringvalidator.LengthAtLeast(1),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The rule ID.",
				MarkdownDescription: "The rule ID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"invocation_mode": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The invocation mode for this rule. Before-publish rules are invoked before a message is published.",
				MarkdownDescription: "The invocation mode for this rule. Before-publish rules are invoked before a message is published.",
				Validators: []validator.String{
					stringvalidator.OneOf("BEFORE_PUBLISH"),
				},
				Default: stringdefault.StaticString("BEFORE_PUBLISH"),
			},
			"status": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The status of the rule. Rules can be enabled or disabled.",
				MarkdownDescription: "The status of the rule. Rules can be enabled or disabled.",
				Validators: []validator.String{
					stringvalidator.OneOf("enabled", "disabled"),
				},
				Default: stringdefault.StaticString("enabled"),
			},
			"target": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"headers": schema.ListNestedAttribute{
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									Optional:            true,
									Description:         "The name of the header.",
									MarkdownDescription: "The name of the header.",
									Validators: []validator.String{
										stringvalidator.LengthAtLeast(1),
									},
								},
								"value": schema.StringAttribute{
									Optional:            true,
									Description:         "The value of the header.",
									MarkdownDescription: "The value of the header.",
									Validators: []validator.String{
										stringvalidator.LengthAtLeast(1),
									},
								},
							},
							CustomType: HeadersType{
								ObjectType: types.ObjectType{
									AttrTypes: HeadersValue{}.AttributeTypes(ctx),
								},
							},
						},
						Optional: true,
					},
					"url": schema.StringAttribute{
						Required:            true,
						Description:         "The webhook URL that Ably will POST events to before publishing.",
						MarkdownDescription: "The webhook URL that Ably will POST events to before publishing.",
						Validators: []validator.String{
							stringvalidator.LengthAtLeast(1),
						},
					},
				},
				CustomType: TargetType{
					ObjectType: types.ObjectType{
						AttrTypes: TargetValue{}.AttributeTypes(ctx),
					},
				},
				Required:            true,
				Description:         "The target for the rule, specifying the webhook endpoint to call.",
				MarkdownDescription: "The target for the rule, specifying the webhook endpoint to call.",
			},
		},
	}
}

type RuleBeforePublishWebhookModel struct {
	AppId               types.String             `tfsdk:"app_id"`
	BeforePublishConfig BeforePublishConfigValue `tfsdk:"before_publish_config"`
	ChatRoomFilter      types.String             `tfsdk:"chat_room_filter"`
	Id                  types.String             `tfsdk:"id"`
	InvocationMode      types.String             `tfsdk:"invocation_mode"`
	Status              types.String             `tfsdk:"status"`
	Target              TargetValue              `tfsdk:"target"`
}

var _ basetypes.ObjectTypable = BeforePublishConfigType{}

type BeforePublishConfigType struct {
	basetypes.ObjectType
}

func (t BeforePublishConfigType) Equal(o attr.Type) bool {
	other, ok := o.(BeforePublishConfigType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t BeforePublishConfigType) String() string {
	return "BeforePublishConfigType"
}

func (t BeforePublishConfigType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	failedActionAttribute, ok := attributes["failed_action"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`failed_action is missing from object`)

		return nil, diags
	}

	failedActionVal, ok := failedActionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`failed_action expected to be basetypes.StringValue, was: %T`, failedActionAttribute))
	}

	maxRetriesAttribute, ok := attributes["max_retries"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_retries is missing from object`)

		return nil, diags
	}

	maxRetriesVal, ok := maxRetriesAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_retries expected to be basetypes.Int64Value, was: %T`, maxRetriesAttribute))
	}

	retryTimeoutAttribute, ok := attributes["retry_timeout"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`retry_timeout is missing from object`)

		return nil, diags
	}

	retryTimeoutVal, ok := retryTimeoutAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`retry_timeout expected to be basetypes.Int64Value, was: %T`, retryTimeoutAttribute))
	}

	tooManyRequestsActionAttribute, ok := attributes["too_many_requests_action"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`too_many_requests_action is missing from object`)

		return nil, diags
	}

	tooManyRequestsActionVal, ok := tooManyRequestsActionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`too_many_requests_action expected to be basetypes.StringValue, was: %T`, tooManyRequestsActionAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return BeforePublishConfigValue{
		FailedAction:          failedActionVal,
		MaxRetries:            maxRetriesVal,
		RetryTimeout:          retryTimeoutVal,
		TooManyRequestsAction: tooManyRequestsActionVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewBeforePublishConfigValueNull() BeforePublishConfigValue {
	return BeforePublishConfigValue{
		state: attr.ValueStateNull,
	}
}

func NewBeforePublishConfigValueUnknown() BeforePublishConfigValue {
	return BeforePublishConfigValue{
		state: attr.ValueStateUnknown,
	}
}

func NewBeforePublishConfigValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (BeforePublishConfigValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing BeforePublishConfigValue Attribute Value",
				"While creating a BeforePublishConfigValue value, a missing attribute value was detected. "+
					"A BeforePublishConfigValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BeforePublishConfigValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid BeforePublishConfigValue Attribute Type",
				"While creating a BeforePublishConfigValue value, an invalid attribute value was detected. "+
					"A BeforePublishConfigValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BeforePublishConfigValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("BeforePublishConfigValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra BeforePublishConfigValue Attribute Value",
				"While creating a BeforePublishConfigValue value, an extra attribute value was detected. "+
					"A BeforePublishConfigValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra BeforePublishConfigValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewBeforePublishConfigValueUnknown(), diags
	}

	failedActionAttribute, ok := attributes["failed_action"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`failed_action is missing from object`)

		return NewBeforePublishConfigValueUnknown(), diags
	}

	failedActionVal, ok := failedActionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`failed_action expected to be basetypes.StringValue, was: %T`, failedActionAttribute))
	}

	maxRetriesAttribute, ok := attributes["max_retries"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_retries is missing from object`)

		return NewBeforePublishConfigValueUnknown(), diags
	}

	maxRetriesVal, ok := maxRetriesAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_retries expected to be basetypes.Int64Value, was: %T`, maxRetriesAttribute))
	}

	retryTimeoutAttribute, ok := attributes["retry_timeout"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`retry_timeout is missing from object`)

		return NewBeforePublishConfigValueUnknown(), diags
	}

	retryTimeoutVal, ok := retryTimeoutAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`retry_timeout expected to be basetypes.Int64Value, was: %T`, retryTimeoutAttribute))
	}

	tooManyRequestsActionAttribute, ok := attributes["too_many_requests_action"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`too_many_requests_action is missing from object`)

		return NewBeforePublishConfigValueUnknown(), diags
	}

	tooManyRequestsActionVal, ok := tooManyRequestsActionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`too_many_requests_action expected to be basetypes.StringValue, was: %T`, tooManyRequestsActionAttribute))
	}

	if diags.HasError() {
		return NewBeforePublishConfigValueUnknown(), diags
	}

	return BeforePublishConfigValue{
		FailedAction:          failedActionVal,
		MaxRetries:            maxRetriesVal,
		RetryTimeout:          retryTimeoutVal,
		TooManyRequestsAction: tooManyRequestsActionVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewBeforePublishConfigValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) BeforePublishConfigValue {
	object, diags := NewBeforePublishConfigValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewBeforePublishConfigValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t BeforePublishConfigType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewBeforePublishConfigValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewBeforePublishConfigValueUnknown(), nil
	}

	if in.IsNull() {
		return NewBeforePublishConfigValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewBeforePublishConfigValueMust(BeforePublishConfigValue{}.AttributeTypes(ctx), attributes), nil
}

func (t BeforePublishConfigType) ValueType(ctx context.Context) attr.Value {
	return BeforePublishConfigValue{}
}

var _ basetypes.ObjectValuable = BeforePublishConfigValue{}

type BeforePublishConfigValue struct {
	FailedAction          basetypes.StringValue `tfsdk:"failed_action"`
	MaxRetries            basetypes.Int64Value  `tfsdk:"max_retries"`
	RetryTimeout          basetypes.Int64Value  `tfsdk:"retry_timeout"`
	TooManyRequestsAction basetypes.StringValue `tfsdk:"too_many_requests_action"`
	state                 attr.ValueState
}

func (v BeforePublishConfigValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["failed_action"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["max_retries"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["retry_timeout"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["too_many_requests_action"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.FailedAction.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["failed_action"] = val

		val, err = v.MaxRetries.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["max_retries"] = val

		val, err = v.RetryTimeout.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["retry_timeout"] = val

		val, err = v.TooManyRequestsAction.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["too_many_requests_action"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v BeforePublishConfigValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v BeforePublishConfigValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v BeforePublishConfigValue) String() string {
	return "BeforePublishConfigValue"
}

func (v BeforePublishConfigValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"failed_action":            basetypes.StringType{},
		"max_retries":              basetypes.Int64Type{},
		"retry_timeout":            basetypes.Int64Type{},
		"too_many_requests_action": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"failed_action":            v.FailedAction,
			"max_retries":              v.MaxRetries,
			"retry_timeout":            v.RetryTimeout,
			"too_many_requests_action": v.TooManyRequestsAction,
		})

	return objVal, diags
}

func (v BeforePublishConfigValue) Equal(o attr.Value) bool {
	other, ok := o.(BeforePublishConfigValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.FailedAction.Equal(other.FailedAction) {
		return false
	}

	if !v.MaxRetries.Equal(other.MaxRetries) {
		return false
	}

	if !v.RetryTimeout.Equal(other.RetryTimeout) {
		return false
	}

	if !v.TooManyRequestsAction.Equal(other.TooManyRequestsAction) {
		return false
	}

	return true
}

func (v BeforePublishConfigValue) Type(ctx context.Context) attr.Type {
	return BeforePublishConfigType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v BeforePublishConfigValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"failed_action":            basetypes.StringType{},
		"max_retries":              basetypes.Int64Type{},
		"retry_timeout":            basetypes.Int64Type{},
		"too_many_requests_action": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = TargetType{}

type TargetType struct {
	basetypes.ObjectType
}

func (t TargetType) Equal(o attr.Type) bool {
	other, ok := o.(TargetType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TargetType) String() string {
	return "TargetType"
}

func (t TargetType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	headersAttribute, ok := attributes["headers"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`headers is missing from object`)

		return nil, diags
	}

	headersVal, ok := headersAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`headers expected to be basetypes.ListValue, was: %T`, headersAttribute))
	}

	urlAttribute, ok := attributes["url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`url is missing from object`)

		return nil, diags
	}

	urlVal, ok := urlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`url expected to be basetypes.StringValue, was: %T`, urlAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TargetValue{
		Headers: headersVal,
		Url:     urlVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewTargetValueNull() TargetValue {
	return TargetValue{
		state: attr.ValueStateNull,
	}
}

func NewTargetValueUnknown() TargetValue {
	return TargetValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTargetValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TargetValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TargetValue Attribute Value",
				"While creating a TargetValue value, a missing attribute value was detected. "+
					"A TargetValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TargetValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TargetValue Attribute Type",
				"While creating a TargetValue value, an invalid attribute value was detected. "+
					"A TargetValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TargetValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TargetValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TargetValue Attribute Value",
				"While creating a TargetValue value, an extra attribute value was detected. "+
					"A TargetValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TargetValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTargetValueUnknown(), diags
	}

	headersAttribute, ok := attributes["headers"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`headers is missing from object`)

		return NewTargetValueUnknown(), diags
	}

	headersVal, ok := headersAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`headers expected to be basetypes.ListValue, was: %T`, headersAttribute))
	}

	urlAttribute, ok := attributes["url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`url is missing from object`)

		return NewTargetValueUnknown(), diags
	}

	urlVal, ok := urlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`url expected to be basetypes.StringValue, was: %T`, urlAttribute))
	}

	if diags.HasError() {
		return NewTargetValueUnknown(), diags
	}

	return TargetValue{
		Headers: headersVal,
		Url:     urlVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewTargetValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TargetValue {
	object, diags := NewTargetValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTargetValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TargetType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTargetValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTargetValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTargetValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTargetValueMust(TargetValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TargetType) ValueType(ctx context.Context) attr.Value {
	return TargetValue{}
}

var _ basetypes.ObjectValuable = TargetValue{}

type TargetValue struct {
	Headers basetypes.ListValue   `tfsdk:"headers"`
	Url     basetypes.StringValue `tfsdk:"url"`
	state   attr.ValueState
}

func (v TargetValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["headers"] = basetypes.ListType{
		ElemType: HeadersValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["url"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Headers.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["headers"] = val

		val, err = v.Url.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["url"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TargetValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TargetValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TargetValue) String() string {
	return "TargetValue"
}

func (v TargetValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	headers := types.ListValueMust(
		HeadersType{
			basetypes.ObjectType{
				AttrTypes: HeadersValue{}.AttributeTypes(ctx),
			},
		},
		v.Headers.Elements(),
	)

	if v.Headers.IsNull() {
		headers = types.ListNull(
			HeadersType{
				basetypes.ObjectType{
					AttrTypes: HeadersValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.Headers.IsUnknown() {
		headers = types.ListUnknown(
			HeadersType{
				basetypes.ObjectType{
					AttrTypes: HeadersValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	attributeTypes := map[string]attr.Type{
		"headers": basetypes.ListType{
			ElemType: HeadersValue{}.Type(ctx),
		},
		"url": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"headers": headers,
			"url":     v.Url,
		})

	return objVal, diags
}

func (v TargetValue) Equal(o attr.Value) bool {
	other, ok := o.(TargetValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Headers.Equal(other.Headers) {
		return false
	}

	if !v.Url.Equal(other.Url) {
		return false
	}

	return true
}

func (v TargetValue) Type(ctx context.Context) attr.Type {
	return TargetType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TargetValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"headers": basetypes.ListType{
			ElemType: HeadersValue{}.Type(ctx),
		},
		"url": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = HeadersType{}

type HeadersType struct {
	basetypes.ObjectType
}

func (t HeadersType) Equal(o attr.Type) bool {
	other, ok := o.(HeadersType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t HeadersType) String() string {
	return "HeadersType"
}

func (t HeadersType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return nil, diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return HeadersValue{
		Name:  nameVal,
		Value: valueVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewHeadersValueNull() HeadersValue {
	return HeadersValue{
		state: attr.ValueStateNull,
	}
}

func NewHeadersValueUnknown() HeadersValue {
	return HeadersValue{
		state: attr.ValueStateUnknown,
	}
}

func NewHeadersValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (HeadersValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing HeadersValue Attribute Value",
				"While creating a HeadersValue value, a missing attribute value was detected. "+
					"A HeadersValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("HeadersValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid HeadersValue Attribute Type",
				"While creating a HeadersValue value, an invalid attribute value was detected. "+
					"A HeadersValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("HeadersValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("HeadersValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra HeadersValue Attribute Value",
				"While creating a HeadersValue value, an extra attribute value was detected. "+
					"A HeadersValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra HeadersValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewHeadersValueUnknown(), diags
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewHeadersValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return NewHeadersValueUnknown(), diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute))
	}

	if diags.HasError() {
		return NewHeadersValueUnknown(), diags
	}

	return HeadersValue{
		Name:  nameVal,
		Value: valueVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewHeadersValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) HeadersValue {
	object, diags := NewHeadersValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewHeadersValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t HeadersType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewHeadersValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewHeadersValueUnknown(), nil
	}

	if in.IsNull() {
		return NewHeadersValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewHeadersValueMust(HeadersValue{}.AttributeTypes(ctx), attributes), nil
}

func (t HeadersType) ValueType(ctx context.Context) attr.Value {
	return HeadersValue{}
}

var _ basetypes.ObjectValuable = HeadersValue{}

type HeadersValue struct {
	Name  basetypes.StringValue `tfsdk:"name"`
	Value basetypes.StringValue `tfsdk:"value"`
	state attr.ValueState
}

func (v HeadersValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["value"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Value.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["value"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v HeadersValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v HeadersValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v HeadersValue) String() string {
	return "HeadersValue"
}

func (v HeadersValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"name":  basetypes.StringType{},
		"value": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"name":  v.Name,
			"value": v.Value,
		})

	return objVal, diags
}

func (v HeadersValue) Equal(o attr.Value) bool {
	other, ok := o.(HeadersValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Value.Equal(other.Value) {
		return false
	}

	return true
}

func (v HeadersValue) Type(ctx context.Context) attr.Type {
	return HeadersType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v HeadersValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"name":  basetypes.StringType{},
		"value": basetypes.StringType{},
	}
}
