// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_rule_before_publish_lambda

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func RuleBeforePublishLambdaResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"app_id": schema.StringAttribute{
				Required:            true,
				Description:         "The Ably application ID.",
				MarkdownDescription: "The Ably application ID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"before_publish_config": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"failed_action": schema.StringAttribute{
						Required:            true,
						Description:         "The action to take if the rule invocation fails. `REJECT` prevents the message from being published, `PUBLISH` allows it through.",
						MarkdownDescription: "The action to take if the rule invocation fails. `REJECT` prevents the message from being published, `PUBLISH` allows it through.",
						Validators: []validator.String{
							stringvalidator.OneOf("REJECT", "PUBLISH"),
						},
					},
					"max_retries": schema.Int64Attribute{
						Required:            true,
						Description:         "The maximum number of retry attempts.",
						MarkdownDescription: "The maximum number of retry attempts.",
					},
					"retry_timeout": schema.Int64Attribute{
						Required:            true,
						Description:         "The timeout in milliseconds for retrying the rule invocation.",
						MarkdownDescription: "The timeout in milliseconds for retrying the rule invocation.",
					},
					"too_many_requests_action": schema.StringAttribute{
						Required:            true,
						Description:         "The action to take if the rule invocation returns a rate limit response. `RETRY` will attempt the request again, `FAIL` will invoke the `failedAction`.",
						MarkdownDescription: "The action to take if the rule invocation returns a rate limit response. `RETRY` will attempt the request again, `FAIL` will invoke the `failedAction`.",
						Validators: []validator.String{
							stringvalidator.OneOf("RETRY", "FAIL"),
						},
					},
				},
				CustomType: BeforePublishConfigType{
					ObjectType: types.ObjectType{
						AttrTypes: BeforePublishConfigValue{}.AttributeTypes(ctx),
					},
				},
				Required:            true,
				Description:         "Configuration for before-publish behavior, including retry logic and failure handling.",
				MarkdownDescription: "Configuration for before-publish behavior, including retry logic and failure handling.",
			},
			"chat_room_filter": schema.StringAttribute{
				Optional:            true,
				Description:         "A regular expression that filters messages based on the chat room ID. Only messages matching this pattern will trigger the rule.",
				MarkdownDescription: "A regular expression that filters messages based on the chat room ID. Only messages matching this pattern will trigger the rule.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^/.*/$"), "must be a slash-delimited regular expression, e.g. /room-.*/"),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The rule ID.",
				MarkdownDescription: "The rule ID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"invocation_mode": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The invocation mode for this rule. Before-publish rules are invoked before a message is published.",
				MarkdownDescription: "The invocation mode for this rule. Before-publish rules are invoked before a message is published.",
				Validators: []validator.String{
					stringvalidator.OneOf("BEFORE_PUBLISH"),
				},
				Default: stringdefault.StaticString("BEFORE_PUBLISH"),
			},
			"source": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"channel_filter": schema.StringAttribute{
						Required: true,
					},
					"type": schema.StringAttribute{
						Required: true,
					},
				},
				CustomType: SourceType{
					ObjectType: types.ObjectType{
						AttrTypes: SourceValue{}.AttributeTypes(ctx),
					},
				},
				Optional: true,
			},
			"status": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The status of the rule. Rules can be enabled or disabled.",
				MarkdownDescription: "The status of the rule. Rules can be enabled or disabled.",
				Validators: []validator.String{
					stringvalidator.OneOf("enabled", "disabled"),
				},
				Default: stringdefault.StaticString("enabled"),
			},
			"target": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"authentication": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"access_key_id": schema.StringAttribute{
								Optional: true,
							},
							"assume_role_arn": schema.StringAttribute{
								Optional: true,
							},
							"authentication_mode": schema.StringAttribute{
								Required: true,
							},
							"secret_access_key": schema.StringAttribute{
								Optional: true,
							},
						},
						CustomType: AuthenticationType{
							ObjectType: types.ObjectType{
								AttrTypes: AuthenticationValue{}.AttributeTypes(ctx),
							},
						},
						Required: true,
					},
					"function_name": schema.StringAttribute{
						Required:            true,
						Description:         "The name of your AWS Lambda function.",
						MarkdownDescription: "The name of your AWS Lambda function.",
					},
					"region": schema.StringAttribute{
						Required:            true,
						Description:         "The AWS region in which your Lambda function is hosted. See the <a href=\"https://docs.aws.amazon.com/general/latest/gr/rande.html#lambda_region\">AWS documentation</a> for more detail.",
						MarkdownDescription: "The AWS region in which your Lambda function is hosted. See the <a href=\"https://docs.aws.amazon.com/general/latest/gr/rande.html#lambda_region\">AWS documentation</a> for more detail.",
					},
				},
				CustomType: TargetType{
					ObjectType: types.ObjectType{
						AttrTypes: TargetValue{}.AttributeTypes(ctx),
					},
				},
				Required:            true,
				Description:         "The target for the rule, specifying the AWS Lambda function to invoke.",
				MarkdownDescription: "The target for the rule, specifying the AWS Lambda function to invoke.",
			},
		},
	}
}

type RuleBeforePublishLambdaModel struct {
	AppId               types.String             `tfsdk:"app_id"`
	BeforePublishConfig BeforePublishConfigValue `tfsdk:"before_publish_config"`
	ChatRoomFilter      types.String             `tfsdk:"chat_room_filter"`
	Id                  types.String             `tfsdk:"id"`
	InvocationMode      types.String             `tfsdk:"invocation_mode"`
	Source              SourceValue              `tfsdk:"source"`
	Status              types.String             `tfsdk:"status"`
	Target              TargetValue              `tfsdk:"target"`
}

var _ basetypes.ObjectTypable = BeforePublishConfigType{}

type BeforePublishConfigType struct {
	basetypes.ObjectType
}

func (t BeforePublishConfigType) Equal(o attr.Type) bool {
	other, ok := o.(BeforePublishConfigType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t BeforePublishConfigType) String() string {
	return "BeforePublishConfigType"
}

func (t BeforePublishConfigType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	failedActionAttribute, ok := attributes["failed_action"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`failed_action is missing from object`)

		return nil, diags
	}

	failedActionVal, ok := failedActionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`failed_action expected to be basetypes.StringValue, was: %T`, failedActionAttribute))
	}

	maxRetriesAttribute, ok := attributes["max_retries"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_retries is missing from object`)

		return nil, diags
	}

	maxRetriesVal, ok := maxRetriesAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_retries expected to be basetypes.Int64Value, was: %T`, maxRetriesAttribute))
	}

	retryTimeoutAttribute, ok := attributes["retry_timeout"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`retry_timeout is missing from object`)

		return nil, diags
	}

	retryTimeoutVal, ok := retryTimeoutAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`retry_timeout expected to be basetypes.Int64Value, was: %T`, retryTimeoutAttribute))
	}

	tooManyRequestsActionAttribute, ok := attributes["too_many_requests_action"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`too_many_requests_action is missing from object`)

		return nil, diags
	}

	tooManyRequestsActionVal, ok := tooManyRequestsActionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`too_many_requests_action expected to be basetypes.StringValue, was: %T`, tooManyRequestsActionAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return BeforePublishConfigValue{
		FailedAction:          failedActionVal,
		MaxRetries:            maxRetriesVal,
		RetryTimeout:          retryTimeoutVal,
		TooManyRequestsAction: tooManyRequestsActionVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewBeforePublishConfigValueNull() BeforePublishConfigValue {
	return BeforePublishConfigValue{
		state: attr.ValueStateNull,
	}
}

func NewBeforePublishConfigValueUnknown() BeforePublishConfigValue {
	return BeforePublishConfigValue{
		state: attr.ValueStateUnknown,
	}
}

func NewBeforePublishConfigValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (BeforePublishConfigValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing BeforePublishConfigValue Attribute Value",
				"While creating a BeforePublishConfigValue value, a missing attribute value was detected. "+
					"A BeforePublishConfigValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BeforePublishConfigValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid BeforePublishConfigValue Attribute Type",
				"While creating a BeforePublishConfigValue value, an invalid attribute value was detected. "+
					"A BeforePublishConfigValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BeforePublishConfigValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("BeforePublishConfigValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra BeforePublishConfigValue Attribute Value",
				"While creating a BeforePublishConfigValue value, an extra attribute value was detected. "+
					"A BeforePublishConfigValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra BeforePublishConfigValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewBeforePublishConfigValueUnknown(), diags
	}

	failedActionAttribute, ok := attributes["failed_action"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`failed_action is missing from object`)

		return NewBeforePublishConfigValueUnknown(), diags
	}

	failedActionVal, ok := failedActionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`failed_action expected to be basetypes.StringValue, was: %T`, failedActionAttribute))
	}

	maxRetriesAttribute, ok := attributes["max_retries"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_retries is missing from object`)

		return NewBeforePublishConfigValueUnknown(), diags
	}

	maxRetriesVal, ok := maxRetriesAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_retries expected to be basetypes.Int64Value, was: %T`, maxRetriesAttribute))
	}

	retryTimeoutAttribute, ok := attributes["retry_timeout"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`retry_timeout is missing from object`)

		return NewBeforePublishConfigValueUnknown(), diags
	}

	retryTimeoutVal, ok := retryTimeoutAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`retry_timeout expected to be basetypes.Int64Value, was: %T`, retryTimeoutAttribute))
	}

	tooManyRequestsActionAttribute, ok := attributes["too_many_requests_action"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`too_many_requests_action is missing from object`)

		return NewBeforePublishConfigValueUnknown(), diags
	}

	tooManyRequestsActionVal, ok := tooManyRequestsActionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`too_many_requests_action expected to be basetypes.StringValue, was: %T`, tooManyRequestsActionAttribute))
	}

	if diags.HasError() {
		return NewBeforePublishConfigValueUnknown(), diags
	}

	return BeforePublishConfigValue{
		FailedAction:          failedActionVal,
		MaxRetries:            maxRetriesVal,
		RetryTimeout:          retryTimeoutVal,
		TooManyRequestsAction: tooManyRequestsActionVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewBeforePublishConfigValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) BeforePublishConfigValue {
	object, diags := NewBeforePublishConfigValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewBeforePublishConfigValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t BeforePublishConfigType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewBeforePublishConfigValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewBeforePublishConfigValueUnknown(), nil
	}

	if in.IsNull() {
		return NewBeforePublishConfigValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewBeforePublishConfigValueMust(BeforePublishConfigValue{}.AttributeTypes(ctx), attributes), nil
}

func (t BeforePublishConfigType) ValueType(ctx context.Context) attr.Value {
	return BeforePublishConfigValue{}
}

var _ basetypes.ObjectValuable = BeforePublishConfigValue{}

type BeforePublishConfigValue struct {
	FailedAction          basetypes.StringValue `tfsdk:"failed_action"`
	MaxRetries            basetypes.Int64Value  `tfsdk:"max_retries"`
	RetryTimeout          basetypes.Int64Value  `tfsdk:"retry_timeout"`
	TooManyRequestsAction basetypes.StringValue `tfsdk:"too_many_requests_action"`
	state                 attr.ValueState
}

func (v BeforePublishConfigValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["failed_action"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["max_retries"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["retry_timeout"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["too_many_requests_action"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.FailedAction.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["failed_action"] = val

		val, err = v.MaxRetries.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["max_retries"] = val

		val, err = v.RetryTimeout.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["retry_timeout"] = val

		val, err = v.TooManyRequestsAction.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["too_many_requests_action"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v BeforePublishConfigValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v BeforePublishConfigValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v BeforePublishConfigValue) String() string {
	return "BeforePublishConfigValue"
}

func (v BeforePublishConfigValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"failed_action":            basetypes.StringType{},
		"max_retries":              basetypes.Int64Type{},
		"retry_timeout":            basetypes.Int64Type{},
		"too_many_requests_action": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"failed_action":            v.FailedAction,
			"max_retries":              v.MaxRetries,
			"retry_timeout":            v.RetryTimeout,
			"too_many_requests_action": v.TooManyRequestsAction,
		})

	return objVal, diags
}

func (v BeforePublishConfigValue) Equal(o attr.Value) bool {
	other, ok := o.(BeforePublishConfigValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.FailedAction.Equal(other.FailedAction) {
		return false
	}

	if !v.MaxRetries.Equal(other.MaxRetries) {
		return false
	}

	if !v.RetryTimeout.Equal(other.RetryTimeout) {
		return false
	}

	if !v.TooManyRequestsAction.Equal(other.TooManyRequestsAction) {
		return false
	}

	return true
}

func (v BeforePublishConfigValue) Type(ctx context.Context) attr.Type {
	return BeforePublishConfigType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v BeforePublishConfigValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"failed_action":            basetypes.StringType{},
		"max_retries":              basetypes.Int64Type{},
		"retry_timeout":            basetypes.Int64Type{},
		"too_many_requests_action": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = SourceType{}

type SourceType struct {
	basetypes.ObjectType
}

func (t SourceType) Equal(o attr.Type) bool {
	other, ok := o.(SourceType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SourceType) String() string {
	return "SourceType"
}

func (t SourceType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	channelFilterAttribute, ok := attributes["channel_filter"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`channel_filter is missing from object`)

		return nil, diags
	}

	channelFilterVal, ok := channelFilterAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`channel_filter expected to be basetypes.StringValue, was: %T`, channelFilterAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return SourceValue{
		ChannelFilter: channelFilterVal,
		SourceType:    typeVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewSourceValueNull() SourceValue {
	return SourceValue{
		state: attr.ValueStateNull,
	}
}

func NewSourceValueUnknown() SourceValue {
	return SourceValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSourceValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SourceValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SourceValue Attribute Value",
				"While creating a SourceValue value, a missing attribute value was detected. "+
					"A SourceValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SourceValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SourceValue Attribute Type",
				"While creating a SourceValue value, an invalid attribute value was detected. "+
					"A SourceValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SourceValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SourceValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SourceValue Attribute Value",
				"While creating a SourceValue value, an extra attribute value was detected. "+
					"A SourceValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SourceValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSourceValueUnknown(), diags
	}

	channelFilterAttribute, ok := attributes["channel_filter"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`channel_filter is missing from object`)

		return NewSourceValueUnknown(), diags
	}

	channelFilterVal, ok := channelFilterAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`channel_filter expected to be basetypes.StringValue, was: %T`, channelFilterAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewSourceValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewSourceValueUnknown(), diags
	}

	return SourceValue{
		ChannelFilter: channelFilterVal,
		SourceType:    typeVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewSourceValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SourceValue {
	object, diags := NewSourceValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewSourceValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SourceType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSourceValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSourceValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSourceValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSourceValueMust(SourceValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SourceType) ValueType(ctx context.Context) attr.Value {
	return SourceValue{}
}

var _ basetypes.ObjectValuable = SourceValue{}

type SourceValue struct {
	ChannelFilter basetypes.StringValue `tfsdk:"channel_filter"`
	SourceType    basetypes.StringValue `tfsdk:"type"`
	state         attr.ValueState
}

func (v SourceValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["channel_filter"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.ChannelFilter.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["channel_filter"] = val

		val, err = v.SourceType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SourceValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SourceValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SourceValue) String() string {
	return "SourceValue"
}

func (v SourceValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"channel_filter": basetypes.StringType{},
		"type":           basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"channel_filter": v.ChannelFilter,
			"type":           v.SourceType,
		})

	return objVal, diags
}

func (v SourceValue) Equal(o attr.Value) bool {
	other, ok := o.(SourceValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ChannelFilter.Equal(other.ChannelFilter) {
		return false
	}

	if !v.SourceType.Equal(other.SourceType) {
		return false
	}

	return true
}

func (v SourceValue) Type(ctx context.Context) attr.Type {
	return SourceType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SourceValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"channel_filter": basetypes.StringType{},
		"type":           basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = TargetType{}

type TargetType struct {
	basetypes.ObjectType
}

func (t TargetType) Equal(o attr.Type) bool {
	other, ok := o.(TargetType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TargetType) String() string {
	return "TargetType"
}

func (t TargetType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	authenticationAttribute, ok := attributes["authentication"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`authentication is missing from object`)

		return nil, diags
	}

	authenticationVal, ok := authenticationAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`authentication expected to be basetypes.ObjectValue, was: %T`, authenticationAttribute))
	}

	functionNameAttribute, ok := attributes["function_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`function_name is missing from object`)

		return nil, diags
	}

	functionNameVal, ok := functionNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`function_name expected to be basetypes.StringValue, was: %T`, functionNameAttribute))
	}

	regionAttribute, ok := attributes["region"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region is missing from object`)

		return nil, diags
	}

	regionVal, ok := regionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region expected to be basetypes.StringValue, was: %T`, regionAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TargetValue{
		Authentication: authenticationVal,
		FunctionName:   functionNameVal,
		Region:         regionVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewTargetValueNull() TargetValue {
	return TargetValue{
		state: attr.ValueStateNull,
	}
}

func NewTargetValueUnknown() TargetValue {
	return TargetValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTargetValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TargetValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TargetValue Attribute Value",
				"While creating a TargetValue value, a missing attribute value was detected. "+
					"A TargetValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TargetValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TargetValue Attribute Type",
				"While creating a TargetValue value, an invalid attribute value was detected. "+
					"A TargetValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TargetValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TargetValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TargetValue Attribute Value",
				"While creating a TargetValue value, an extra attribute value was detected. "+
					"A TargetValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TargetValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTargetValueUnknown(), diags
	}

	authenticationAttribute, ok := attributes["authentication"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`authentication is missing from object`)

		return NewTargetValueUnknown(), diags
	}

	authenticationVal, ok := authenticationAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`authentication expected to be basetypes.ObjectValue, was: %T`, authenticationAttribute))
	}

	functionNameAttribute, ok := attributes["function_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`function_name is missing from object`)

		return NewTargetValueUnknown(), diags
	}

	functionNameVal, ok := functionNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`function_name expected to be basetypes.StringValue, was: %T`, functionNameAttribute))
	}

	regionAttribute, ok := attributes["region"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region is missing from object`)

		return NewTargetValueUnknown(), diags
	}

	regionVal, ok := regionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region expected to be basetypes.StringValue, was: %T`, regionAttribute))
	}

	if diags.HasError() {
		return NewTargetValueUnknown(), diags
	}

	return TargetValue{
		Authentication: authenticationVal,
		FunctionName:   functionNameVal,
		Region:         regionVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewTargetValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TargetValue {
	object, diags := NewTargetValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTargetValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TargetType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTargetValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTargetValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTargetValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTargetValueMust(TargetValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TargetType) ValueType(ctx context.Context) attr.Value {
	return TargetValue{}
}

var _ basetypes.ObjectValuable = TargetValue{}

type TargetValue struct {
	Authentication basetypes.ObjectValue `tfsdk:"authentication"`
	FunctionName   basetypes.StringValue `tfsdk:"function_name"`
	Region         basetypes.StringValue `tfsdk:"region"`
	state          attr.ValueState
}

func (v TargetValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["authentication"] = basetypes.ObjectType{
		AttrTypes: AuthenticationValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["function_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["region"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Authentication.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["authentication"] = val

		val, err = v.FunctionName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["function_name"] = val

		val, err = v.Region.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TargetValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TargetValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TargetValue) String() string {
	return "TargetValue"
}

func (v TargetValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var authentication basetypes.ObjectValue

	if v.Authentication.IsNull() {
		authentication = types.ObjectNull(
			AuthenticationValue{}.AttributeTypes(ctx),
		)
	}

	if v.Authentication.IsUnknown() {
		authentication = types.ObjectUnknown(
			AuthenticationValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Authentication.IsNull() && !v.Authentication.IsUnknown() {
		authentication = types.ObjectValueMust(
			AuthenticationValue{}.AttributeTypes(ctx),
			v.Authentication.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"authentication": basetypes.ObjectType{
			AttrTypes: AuthenticationValue{}.AttributeTypes(ctx),
		},
		"function_name": basetypes.StringType{},
		"region":        basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"authentication": authentication,
			"function_name":  v.FunctionName,
			"region":         v.Region,
		})

	return objVal, diags
}

func (v TargetValue) Equal(o attr.Value) bool {
	other, ok := o.(TargetValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Authentication.Equal(other.Authentication) {
		return false
	}

	if !v.FunctionName.Equal(other.FunctionName) {
		return false
	}

	if !v.Region.Equal(other.Region) {
		return false
	}

	return true
}

func (v TargetValue) Type(ctx context.Context) attr.Type {
	return TargetType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TargetValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"authentication": basetypes.ObjectType{
			AttrTypes: AuthenticationValue{}.AttributeTypes(ctx),
		},
		"function_name": basetypes.StringType{},
		"region":        basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = AuthenticationType{}

type AuthenticationType struct {
	basetypes.ObjectType
}

func (t AuthenticationType) Equal(o attr.Type) bool {
	other, ok := o.(AuthenticationType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AuthenticationType) String() string {
	return "AuthenticationType"
}

func (t AuthenticationType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	accessKeyIdAttribute, ok := attributes["access_key_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`access_key_id is missing from object`)

		return nil, diags
	}

	accessKeyIdVal, ok := accessKeyIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`access_key_id expected to be basetypes.StringValue, was: %T`, accessKeyIdAttribute))
	}

	assumeRoleArnAttribute, ok := attributes["assume_role_arn"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`assume_role_arn is missing from object`)

		return nil, diags
	}

	assumeRoleArnVal, ok := assumeRoleArnAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`assume_role_arn expected to be basetypes.StringValue, was: %T`, assumeRoleArnAttribute))
	}

	authenticationModeAttribute, ok := attributes["authentication_mode"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`authentication_mode is missing from object`)

		return nil, diags
	}

	authenticationModeVal, ok := authenticationModeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`authentication_mode expected to be basetypes.StringValue, was: %T`, authenticationModeAttribute))
	}

	secretAccessKeyAttribute, ok := attributes["secret_access_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`secret_access_key is missing from object`)

		return nil, diags
	}

	secretAccessKeyVal, ok := secretAccessKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`secret_access_key expected to be basetypes.StringValue, was: %T`, secretAccessKeyAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AuthenticationValue{
		AccessKeyId:        accessKeyIdVal,
		AssumeRoleArn:      assumeRoleArnVal,
		AuthenticationMode: authenticationModeVal,
		SecretAccessKey:    secretAccessKeyVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewAuthenticationValueNull() AuthenticationValue {
	return AuthenticationValue{
		state: attr.ValueStateNull,
	}
}

func NewAuthenticationValueUnknown() AuthenticationValue {
	return AuthenticationValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAuthenticationValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AuthenticationValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AuthenticationValue Attribute Value",
				"While creating a AuthenticationValue value, a missing attribute value was detected. "+
					"A AuthenticationValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AuthenticationValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AuthenticationValue Attribute Type",
				"While creating a AuthenticationValue value, an invalid attribute value was detected. "+
					"A AuthenticationValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AuthenticationValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AuthenticationValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AuthenticationValue Attribute Value",
				"While creating a AuthenticationValue value, an extra attribute value was detected. "+
					"A AuthenticationValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AuthenticationValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAuthenticationValueUnknown(), diags
	}

	accessKeyIdAttribute, ok := attributes["access_key_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`access_key_id is missing from object`)

		return NewAuthenticationValueUnknown(), diags
	}

	accessKeyIdVal, ok := accessKeyIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`access_key_id expected to be basetypes.StringValue, was: %T`, accessKeyIdAttribute))
	}

	assumeRoleArnAttribute, ok := attributes["assume_role_arn"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`assume_role_arn is missing from object`)

		return NewAuthenticationValueUnknown(), diags
	}

	assumeRoleArnVal, ok := assumeRoleArnAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`assume_role_arn expected to be basetypes.StringValue, was: %T`, assumeRoleArnAttribute))
	}

	authenticationModeAttribute, ok := attributes["authentication_mode"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`authentication_mode is missing from object`)

		return NewAuthenticationValueUnknown(), diags
	}

	authenticationModeVal, ok := authenticationModeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`authentication_mode expected to be basetypes.StringValue, was: %T`, authenticationModeAttribute))
	}

	secretAccessKeyAttribute, ok := attributes["secret_access_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`secret_access_key is missing from object`)

		return NewAuthenticationValueUnknown(), diags
	}

	secretAccessKeyVal, ok := secretAccessKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`secret_access_key expected to be basetypes.StringValue, was: %T`, secretAccessKeyAttribute))
	}

	if diags.HasError() {
		return NewAuthenticationValueUnknown(), diags
	}

	return AuthenticationValue{
		AccessKeyId:        accessKeyIdVal,
		AssumeRoleArn:      assumeRoleArnVal,
		AuthenticationMode: authenticationModeVal,
		SecretAccessKey:    secretAccessKeyVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewAuthenticationValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AuthenticationValue {
	object, diags := NewAuthenticationValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAuthenticationValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AuthenticationType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAuthenticationValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAuthenticationValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAuthenticationValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAuthenticationValueMust(AuthenticationValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AuthenticationType) ValueType(ctx context.Context) attr.Value {
	return AuthenticationValue{}
}

var _ basetypes.ObjectValuable = AuthenticationValue{}

type AuthenticationValue struct {
	AccessKeyId        basetypes.StringValue `tfsdk:"access_key_id"`
	AssumeRoleArn      basetypes.StringValue `tfsdk:"assume_role_arn"`
	AuthenticationMode basetypes.StringValue `tfsdk:"authentication_mode"`
	SecretAccessKey    basetypes.StringValue `tfsdk:"secret_access_key"`
	state              attr.ValueState
}

func (v AuthenticationValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["access_key_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["assume_role_arn"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["authentication_mode"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["secret_access_key"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.AccessKeyId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["access_key_id"] = val

		val, err = v.AssumeRoleArn.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["assume_role_arn"] = val

		val, err = v.AuthenticationMode.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["authentication_mode"] = val

		val, err = v.SecretAccessKey.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["secret_access_key"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AuthenticationValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AuthenticationValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AuthenticationValue) String() string {
	return "AuthenticationValue"
}

func (v AuthenticationValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"access_key_id":       basetypes.StringType{},
		"assume_role_arn":     basetypes.StringType{},
		"authentication_mode": basetypes.StringType{},
		"secret_access_key":   basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"access_key_id":       v.AccessKeyId,
			"assume_role_arn":     v.AssumeRoleArn,
			"authentication_mode": v.AuthenticationMode,
			"secret_access_key":   v.SecretAccessKey,
		})

	return objVal, diags
}

func (v AuthenticationValue) Equal(o attr.Value) bool {
	other, ok := o.(AuthenticationValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AccessKeyId.Equal(other.AccessKeyId) {
		return false
	}

	if !v.AssumeRoleArn.Equal(other.AssumeRoleArn) {
		return false
	}

	if !v.AuthenticationMode.Equal(other.AuthenticationMode) {
		return false
	}

	if !v.SecretAccessKey.Equal(other.SecretAccessKey) {
		return false
	}

	return true
}

func (v AuthenticationValue) Type(ctx context.Context) attr.Type {
	return AuthenticationType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AuthenticationValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"access_key_id":       basetypes.StringType{},
		"assume_role_arn":     basetypes.StringType{},
		"authentication_mode": basetypes.StringType{},
		"secret_access_key":   basetypes.StringType{},
	}
}
