// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_apps

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func AppsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"account_id": schema.StringAttribute{
				Required:            true,
				Description:         "The account ID for which to retrieve the associated applications.",
				MarkdownDescription: "The account ID for which to retrieve the associated applications.",
			},
			"apps": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"_links": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{},
							CustomType: LinksType{
								ObjectType: types.ObjectType{
									AttrTypes: LinksValue{}.AttributeTypes(ctx),
								},
							},
							Computed:            true,
							Description:         "A link self-referencing the app that has been created.",
							MarkdownDescription: "A link self-referencing the app that has been created.",
						},
						"account_id": schema.StringAttribute{
							Computed:            true,
							Description:         "The ID of your Ably account.",
							MarkdownDescription: "The ID of your Ably account.",
						},
						"apns_auth_type": schema.StringAttribute{
							Computed:            true,
							Description:         "The Apple Push Notification service authentication type. Use `certificate` for p12 certificate-based auth, or `token` for p8 key-based auth.",
							MarkdownDescription: "The Apple Push Notification service authentication type. Use `certificate` for p12 certificate-based auth, or `token` for p8 key-based auth.",
						},
						"apns_certificate_configured": schema.BoolAttribute{
							Computed:            true,
							Description:         "Whether a certificate-based APNs configuration is currently active.",
							MarkdownDescription: "Whether a certificate-based APNs configuration is currently active.",
						},
						"apns_issuer_key": schema.StringAttribute{
							Computed:            true,
							Description:         "The Team ID from the Apple Developer account. Used as the issuer when generating APNs authentication tokens.",
							MarkdownDescription: "The Team ID from the Apple Developer account. Used as the issuer when generating APNs authentication tokens.",
						},
						"apns_signing_key_configured": schema.BoolAttribute{
							Computed:            true,
							Description:         "Whether a token-based (p8) APNs signing key is currently configured.",
							MarkdownDescription: "Whether a token-based (p8) APNs signing key is currently configured.",
						},
						"apns_signing_key_id": schema.StringAttribute{
							Computed:            true,
							Description:         "The 10-character Key ID from the Apple Developer portal, associated with the `.p8` signing key.",
							MarkdownDescription: "The 10-character Key ID from the Apple Developer portal, associated with the `.p8` signing key.",
						},
						"apns_topic_header": schema.StringAttribute{
							Computed:            true,
							Description:         "The app's bundle ID (for example, `com.example.myapp`). Used as the `apns-topic` header when sending push notifications.",
							MarkdownDescription: "The app's bundle ID (for example, `com.example.myapp`). Used as the `apns-topic` header when sending push notifications.",
						},
						"apns_use_sandbox_endpoint": schema.BoolAttribute{
							Computed:            true,
							Description:         "Use the Apple Push Notification service sandbox endpoint.",
							MarkdownDescription: "Use the Apple Push Notification service sandbox endpoint.",
						},
						"created": schema.Int64Attribute{
							Computed:            true,
							Description:         "Unix timestamp representing the date and time of creation of the application.",
							MarkdownDescription: "Unix timestamp representing the date and time of creation of the application.",
						},
						"fcm_project_id": schema.StringAttribute{
							Computed:            true,
							Description:         "The unique identifier for the Firebase Cloud Messaging (FCM) project. This ID is used to specify the Firebase project when configuring FCM or other Firebase services.",
							MarkdownDescription: "The unique identifier for the Firebase Cloud Messaging (FCM) project. This ID is used to specify the Firebase project when configuring FCM or other Firebase services.",
						},
						"fcm_service_account_configured": schema.BoolAttribute{
							Computed:            true,
							Description:         "Whether Firebase Cloud Messaging (FCM) service account credentials are currently configured.",
							MarkdownDescription: "Whether Firebase Cloud Messaging (FCM) service account credentials are currently configured.",
						},
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "The application ID.",
							MarkdownDescription: "The application ID.",
						},
						"modified": schema.Int64Attribute{
							Computed:            true,
							Description:         "Unix timestamp representing the date and time of last modification of the application.",
							MarkdownDescription: "Unix timestamp representing the date and time of last modification of the application.",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "The application name.",
							MarkdownDescription: "The application name.",
						},
						"status": schema.StringAttribute{
							Computed:            true,
							Description:         "The status of the application. Can be `enabled` or `disabled`. Enabled means available to accept inbound connections and all services are available.",
							MarkdownDescription: "The status of the application. Can be `enabled` or `disabled`. Enabled means available to accept inbound connections and all services are available.",
						},
						"tls_only": schema.BoolAttribute{
							Computed:            true,
							Description:         "Enforce TLS for all connections. This setting overrides any channel setting.",
							MarkdownDescription: "Enforce TLS for all connections. This setting overrides any channel setting.",
						},
					},
					CustomType: AppsType{
						ObjectType: types.ObjectType{
							AttrTypes: AppsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type AppsModel struct {
	AccountId types.String `tfsdk:"account_id"`
	Apps      types.Set    `tfsdk:"apps"`
}

var _ basetypes.ObjectTypable = AppsType{}

type AppsType struct {
	basetypes.ObjectType
}

func (t AppsType) Equal(o attr.Type) bool {
	other, ok := o.(AppsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AppsType) String() string {
	return "AppsType"
}

func (t AppsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	linksAttribute, ok := attributes["_links"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`_links is missing from object`)

		return nil, diags
	}

	linksVal, ok := linksAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`_links expected to be basetypes.ObjectValue, was: %T`, linksAttribute))
	}

	accountIdAttribute, ok := attributes["account_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`account_id is missing from object`)

		return nil, diags
	}

	accountIdVal, ok := accountIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`account_id expected to be basetypes.StringValue, was: %T`, accountIdAttribute))
	}

	apnsAuthTypeAttribute, ok := attributes["apns_auth_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`apns_auth_type is missing from object`)

		return nil, diags
	}

	apnsAuthTypeVal, ok := apnsAuthTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`apns_auth_type expected to be basetypes.StringValue, was: %T`, apnsAuthTypeAttribute))
	}

	apnsCertificateConfiguredAttribute, ok := attributes["apns_certificate_configured"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`apns_certificate_configured is missing from object`)

		return nil, diags
	}

	apnsCertificateConfiguredVal, ok := apnsCertificateConfiguredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`apns_certificate_configured expected to be basetypes.BoolValue, was: %T`, apnsCertificateConfiguredAttribute))
	}

	apnsIssuerKeyAttribute, ok := attributes["apns_issuer_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`apns_issuer_key is missing from object`)

		return nil, diags
	}

	apnsIssuerKeyVal, ok := apnsIssuerKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`apns_issuer_key expected to be basetypes.StringValue, was: %T`, apnsIssuerKeyAttribute))
	}

	apnsSigningKeyConfiguredAttribute, ok := attributes["apns_signing_key_configured"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`apns_signing_key_configured is missing from object`)

		return nil, diags
	}

	apnsSigningKeyConfiguredVal, ok := apnsSigningKeyConfiguredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`apns_signing_key_configured expected to be basetypes.BoolValue, was: %T`, apnsSigningKeyConfiguredAttribute))
	}

	apnsSigningKeyIdAttribute, ok := attributes["apns_signing_key_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`apns_signing_key_id is missing from object`)

		return nil, diags
	}

	apnsSigningKeyIdVal, ok := apnsSigningKeyIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`apns_signing_key_id expected to be basetypes.StringValue, was: %T`, apnsSigningKeyIdAttribute))
	}

	apnsTopicHeaderAttribute, ok := attributes["apns_topic_header"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`apns_topic_header is missing from object`)

		return nil, diags
	}

	apnsTopicHeaderVal, ok := apnsTopicHeaderAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`apns_topic_header expected to be basetypes.StringValue, was: %T`, apnsTopicHeaderAttribute))
	}

	apnsUseSandboxEndpointAttribute, ok := attributes["apns_use_sandbox_endpoint"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`apns_use_sandbox_endpoint is missing from object`)

		return nil, diags
	}

	apnsUseSandboxEndpointVal, ok := apnsUseSandboxEndpointAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`apns_use_sandbox_endpoint expected to be basetypes.BoolValue, was: %T`, apnsUseSandboxEndpointAttribute))
	}

	createdAttribute, ok := attributes["created"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created is missing from object`)

		return nil, diags
	}

	createdVal, ok := createdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created expected to be basetypes.Int64Value, was: %T`, createdAttribute))
	}

	fcmProjectIdAttribute, ok := attributes["fcm_project_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fcm_project_id is missing from object`)

		return nil, diags
	}

	fcmProjectIdVal, ok := fcmProjectIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fcm_project_id expected to be basetypes.StringValue, was: %T`, fcmProjectIdAttribute))
	}

	fcmServiceAccountConfiguredAttribute, ok := attributes["fcm_service_account_configured"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fcm_service_account_configured is missing from object`)

		return nil, diags
	}

	fcmServiceAccountConfiguredVal, ok := fcmServiceAccountConfiguredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fcm_service_account_configured expected to be basetypes.BoolValue, was: %T`, fcmServiceAccountConfiguredAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	modifiedAttribute, ok := attributes["modified"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`modified is missing from object`)

		return nil, diags
	}

	modifiedVal, ok := modifiedAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`modified expected to be basetypes.Int64Value, was: %T`, modifiedAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return nil, diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	tlsOnlyAttribute, ok := attributes["tls_only"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tls_only is missing from object`)

		return nil, diags
	}

	tlsOnlyVal, ok := tlsOnlyAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tls_only expected to be basetypes.BoolValue, was: %T`, tlsOnlyAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AppsValue{
		Links:                       linksVal,
		AccountId:                   accountIdVal,
		ApnsAuthType:                apnsAuthTypeVal,
		ApnsCertificateConfigured:   apnsCertificateConfiguredVal,
		ApnsIssuerKey:               apnsIssuerKeyVal,
		ApnsSigningKeyConfigured:    apnsSigningKeyConfiguredVal,
		ApnsSigningKeyId:            apnsSigningKeyIdVal,
		ApnsTopicHeader:             apnsTopicHeaderVal,
		ApnsUseSandboxEndpoint:      apnsUseSandboxEndpointVal,
		Created:                     createdVal,
		FcmProjectId:                fcmProjectIdVal,
		FcmServiceAccountConfigured: fcmServiceAccountConfiguredVal,
		Id:                          idVal,
		Modified:                    modifiedVal,
		Name:                        nameVal,
		Status:                      statusVal,
		TlsOnly:                     tlsOnlyVal,
		state:                       attr.ValueStateKnown,
	}, diags
}

func NewAppsValueNull() AppsValue {
	return AppsValue{
		state: attr.ValueStateNull,
	}
}

func NewAppsValueUnknown() AppsValue {
	return AppsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAppsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AppsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AppsValue Attribute Value",
				"While creating a AppsValue value, a missing attribute value was detected. "+
					"A AppsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AppsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AppsValue Attribute Type",
				"While creating a AppsValue value, an invalid attribute value was detected. "+
					"A AppsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AppsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AppsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AppsValue Attribute Value",
				"While creating a AppsValue value, an extra attribute value was detected. "+
					"A AppsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AppsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAppsValueUnknown(), diags
	}

	linksAttribute, ok := attributes["_links"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`_links is missing from object`)

		return NewAppsValueUnknown(), diags
	}

	linksVal, ok := linksAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`_links expected to be basetypes.ObjectValue, was: %T`, linksAttribute))
	}

	accountIdAttribute, ok := attributes["account_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`account_id is missing from object`)

		return NewAppsValueUnknown(), diags
	}

	accountIdVal, ok := accountIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`account_id expected to be basetypes.StringValue, was: %T`, accountIdAttribute))
	}

	apnsAuthTypeAttribute, ok := attributes["apns_auth_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`apns_auth_type is missing from object`)

		return NewAppsValueUnknown(), diags
	}

	apnsAuthTypeVal, ok := apnsAuthTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`apns_auth_type expected to be basetypes.StringValue, was: %T`, apnsAuthTypeAttribute))
	}

	apnsCertificateConfiguredAttribute, ok := attributes["apns_certificate_configured"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`apns_certificate_configured is missing from object`)

		return NewAppsValueUnknown(), diags
	}

	apnsCertificateConfiguredVal, ok := apnsCertificateConfiguredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`apns_certificate_configured expected to be basetypes.BoolValue, was: %T`, apnsCertificateConfiguredAttribute))
	}

	apnsIssuerKeyAttribute, ok := attributes["apns_issuer_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`apns_issuer_key is missing from object`)

		return NewAppsValueUnknown(), diags
	}

	apnsIssuerKeyVal, ok := apnsIssuerKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`apns_issuer_key expected to be basetypes.StringValue, was: %T`, apnsIssuerKeyAttribute))
	}

	apnsSigningKeyConfiguredAttribute, ok := attributes["apns_signing_key_configured"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`apns_signing_key_configured is missing from object`)

		return NewAppsValueUnknown(), diags
	}

	apnsSigningKeyConfiguredVal, ok := apnsSigningKeyConfiguredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`apns_signing_key_configured expected to be basetypes.BoolValue, was: %T`, apnsSigningKeyConfiguredAttribute))
	}

	apnsSigningKeyIdAttribute, ok := attributes["apns_signing_key_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`apns_signing_key_id is missing from object`)

		return NewAppsValueUnknown(), diags
	}

	apnsSigningKeyIdVal, ok := apnsSigningKeyIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`apns_signing_key_id expected to be basetypes.StringValue, was: %T`, apnsSigningKeyIdAttribute))
	}

	apnsTopicHeaderAttribute, ok := attributes["apns_topic_header"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`apns_topic_header is missing from object`)

		return NewAppsValueUnknown(), diags
	}

	apnsTopicHeaderVal, ok := apnsTopicHeaderAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`apns_topic_header expected to be basetypes.StringValue, was: %T`, apnsTopicHeaderAttribute))
	}

	apnsUseSandboxEndpointAttribute, ok := attributes["apns_use_sandbox_endpoint"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`apns_use_sandbox_endpoint is missing from object`)

		return NewAppsValueUnknown(), diags
	}

	apnsUseSandboxEndpointVal, ok := apnsUseSandboxEndpointAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`apns_use_sandbox_endpoint expected to be basetypes.BoolValue, was: %T`, apnsUseSandboxEndpointAttribute))
	}

	createdAttribute, ok := attributes["created"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created is missing from object`)

		return NewAppsValueUnknown(), diags
	}

	createdVal, ok := createdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created expected to be basetypes.Int64Value, was: %T`, createdAttribute))
	}

	fcmProjectIdAttribute, ok := attributes["fcm_project_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fcm_project_id is missing from object`)

		return NewAppsValueUnknown(), diags
	}

	fcmProjectIdVal, ok := fcmProjectIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fcm_project_id expected to be basetypes.StringValue, was: %T`, fcmProjectIdAttribute))
	}

	fcmServiceAccountConfiguredAttribute, ok := attributes["fcm_service_account_configured"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fcm_service_account_configured is missing from object`)

		return NewAppsValueUnknown(), diags
	}

	fcmServiceAccountConfiguredVal, ok := fcmServiceAccountConfiguredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fcm_service_account_configured expected to be basetypes.BoolValue, was: %T`, fcmServiceAccountConfiguredAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewAppsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	modifiedAttribute, ok := attributes["modified"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`modified is missing from object`)

		return NewAppsValueUnknown(), diags
	}

	modifiedVal, ok := modifiedAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`modified expected to be basetypes.Int64Value, was: %T`, modifiedAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewAppsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return NewAppsValueUnknown(), diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	tlsOnlyAttribute, ok := attributes["tls_only"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tls_only is missing from object`)

		return NewAppsValueUnknown(), diags
	}

	tlsOnlyVal, ok := tlsOnlyAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tls_only expected to be basetypes.BoolValue, was: %T`, tlsOnlyAttribute))
	}

	if diags.HasError() {
		return NewAppsValueUnknown(), diags
	}

	return AppsValue{
		Links:                       linksVal,
		AccountId:                   accountIdVal,
		ApnsAuthType:                apnsAuthTypeVal,
		ApnsCertificateConfigured:   apnsCertificateConfiguredVal,
		ApnsIssuerKey:               apnsIssuerKeyVal,
		ApnsSigningKeyConfigured:    apnsSigningKeyConfiguredVal,
		ApnsSigningKeyId:            apnsSigningKeyIdVal,
		ApnsTopicHeader:             apnsTopicHeaderVal,
		ApnsUseSandboxEndpoint:      apnsUseSandboxEndpointVal,
		Created:                     createdVal,
		FcmProjectId:                fcmProjectIdVal,
		FcmServiceAccountConfigured: fcmServiceAccountConfiguredVal,
		Id:                          idVal,
		Modified:                    modifiedVal,
		Name:                        nameVal,
		Status:                      statusVal,
		TlsOnly:                     tlsOnlyVal,
		state:                       attr.ValueStateKnown,
	}, diags
}

func NewAppsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AppsValue {
	object, diags := NewAppsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAppsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AppsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAppsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAppsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAppsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAppsValueMust(AppsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AppsType) ValueType(ctx context.Context) attr.Value {
	return AppsValue{}
}

var _ basetypes.ObjectValuable = AppsValue{}

type AppsValue struct {
	Links                       basetypes.ObjectValue `tfsdk:"_links"`
	AccountId                   basetypes.StringValue `tfsdk:"account_id"`
	ApnsAuthType                basetypes.StringValue `tfsdk:"apns_auth_type"`
	ApnsCertificateConfigured   basetypes.BoolValue   `tfsdk:"apns_certificate_configured"`
	ApnsIssuerKey               basetypes.StringValue `tfsdk:"apns_issuer_key"`
	ApnsSigningKeyConfigured    basetypes.BoolValue   `tfsdk:"apns_signing_key_configured"`
	ApnsSigningKeyId            basetypes.StringValue `tfsdk:"apns_signing_key_id"`
	ApnsTopicHeader             basetypes.StringValue `tfsdk:"apns_topic_header"`
	ApnsUseSandboxEndpoint      basetypes.BoolValue   `tfsdk:"apns_use_sandbox_endpoint"`
	Created                     basetypes.Int64Value  `tfsdk:"created"`
	FcmProjectId                basetypes.StringValue `tfsdk:"fcm_project_id"`
	FcmServiceAccountConfigured basetypes.BoolValue   `tfsdk:"fcm_service_account_configured"`
	Id                          basetypes.StringValue `tfsdk:"id"`
	Modified                    basetypes.Int64Value  `tfsdk:"modified"`
	Name                        basetypes.StringValue `tfsdk:"name"`
	Status                      basetypes.StringValue `tfsdk:"status"`
	TlsOnly                     basetypes.BoolValue   `tfsdk:"tls_only"`
	state                       attr.ValueState
}

func (v AppsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 17)

	var val tftypes.Value
	var err error

	attrTypes["_links"] = basetypes.ObjectType{
		AttrTypes: LinksValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["account_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["apns_auth_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["apns_certificate_configured"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["apns_issuer_key"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["apns_signing_key_configured"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["apns_signing_key_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["apns_topic_header"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["apns_use_sandbox_endpoint"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["created"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["fcm_project_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["fcm_service_account_configured"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["modified"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["status"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["tls_only"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 17)

		val, err = v.Links.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["_links"] = val

		val, err = v.AccountId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["account_id"] = val

		val, err = v.ApnsAuthType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["apns_auth_type"] = val

		val, err = v.ApnsCertificateConfigured.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["apns_certificate_configured"] = val

		val, err = v.ApnsIssuerKey.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["apns_issuer_key"] = val

		val, err = v.ApnsSigningKeyConfigured.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["apns_signing_key_configured"] = val

		val, err = v.ApnsSigningKeyId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["apns_signing_key_id"] = val

		val, err = v.ApnsTopicHeader.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["apns_topic_header"] = val

		val, err = v.ApnsUseSandboxEndpoint.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["apns_use_sandbox_endpoint"] = val

		val, err = v.Created.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created"] = val

		val, err = v.FcmProjectId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["fcm_project_id"] = val

		val, err = v.FcmServiceAccountConfigured.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["fcm_service_account_configured"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Modified.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["modified"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Status.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status"] = val

		val, err = v.TlsOnly.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tls_only"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AppsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AppsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AppsValue) String() string {
	return "AppsValue"
}

func (v AppsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var links basetypes.ObjectValue

	if v.Links.IsNull() {
		links = types.ObjectNull(
			LinksValue{}.AttributeTypes(ctx),
		)
	}

	if v.Links.IsUnknown() {
		links = types.ObjectUnknown(
			LinksValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Links.IsNull() && !v.Links.IsUnknown() {
		links = types.ObjectValueMust(
			LinksValue{}.AttributeTypes(ctx),
			v.Links.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"_links": basetypes.ObjectType{
			AttrTypes: LinksValue{}.AttributeTypes(ctx),
		},
		"account_id":                     basetypes.StringType{},
		"apns_auth_type":                 basetypes.StringType{},
		"apns_certificate_configured":    basetypes.BoolType{},
		"apns_issuer_key":                basetypes.StringType{},
		"apns_signing_key_configured":    basetypes.BoolType{},
		"apns_signing_key_id":            basetypes.StringType{},
		"apns_topic_header":              basetypes.StringType{},
		"apns_use_sandbox_endpoint":      basetypes.BoolType{},
		"created":                        basetypes.Int64Type{},
		"fcm_project_id":                 basetypes.StringType{},
		"fcm_service_account_configured": basetypes.BoolType{},
		"id":                             basetypes.StringType{},
		"modified":                       basetypes.Int64Type{},
		"name":                           basetypes.StringType{},
		"status":                         basetypes.StringType{},
		"tls_only":                       basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"_links":                         links,
			"account_id":                     v.AccountId,
			"apns_auth_type":                 v.ApnsAuthType,
			"apns_certificate_configured":    v.ApnsCertificateConfigured,
			"apns_issuer_key":                v.ApnsIssuerKey,
			"apns_signing_key_configured":    v.ApnsSigningKeyConfigured,
			"apns_signing_key_id":            v.ApnsSigningKeyId,
			"apns_topic_header":              v.ApnsTopicHeader,
			"apns_use_sandbox_endpoint":      v.ApnsUseSandboxEndpoint,
			"created":                        v.Created,
			"fcm_project_id":                 v.FcmProjectId,
			"fcm_service_account_configured": v.FcmServiceAccountConfigured,
			"id":                             v.Id,
			"modified":                       v.Modified,
			"name":                           v.Name,
			"status":                         v.Status,
			"tls_only":                       v.TlsOnly,
		})

	return objVal, diags
}

func (v AppsValue) Equal(o attr.Value) bool {
	other, ok := o.(AppsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Links.Equal(other.Links) {
		return false
	}

	if !v.AccountId.Equal(other.AccountId) {
		return false
	}

	if !v.ApnsAuthType.Equal(other.ApnsAuthType) {
		return false
	}

	if !v.ApnsCertificateConfigured.Equal(other.ApnsCertificateConfigured) {
		return false
	}

	if !v.ApnsIssuerKey.Equal(other.ApnsIssuerKey) {
		return false
	}

	if !v.ApnsSigningKeyConfigured.Equal(other.ApnsSigningKeyConfigured) {
		return false
	}

	if !v.ApnsSigningKeyId.Equal(other.ApnsSigningKeyId) {
		return false
	}

	if !v.ApnsTopicHeader.Equal(other.ApnsTopicHeader) {
		return false
	}

	if !v.ApnsUseSandboxEndpoint.Equal(other.ApnsUseSandboxEndpoint) {
		return false
	}

	if !v.Created.Equal(other.Created) {
		return false
	}

	if !v.FcmProjectId.Equal(other.FcmProjectId) {
		return false
	}

	if !v.FcmServiceAccountConfigured.Equal(other.FcmServiceAccountConfigured) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Modified.Equal(other.Modified) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Status.Equal(other.Status) {
		return false
	}

	if !v.TlsOnly.Equal(other.TlsOnly) {
		return false
	}

	return true
}

func (v AppsValue) Type(ctx context.Context) attr.Type {
	return AppsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AppsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"_links": basetypes.ObjectType{
			AttrTypes: LinksValue{}.AttributeTypes(ctx),
		},
		"account_id":                     basetypes.StringType{},
		"apns_auth_type":                 basetypes.StringType{},
		"apns_certificate_configured":    basetypes.BoolType{},
		"apns_issuer_key":                basetypes.StringType{},
		"apns_signing_key_configured":    basetypes.BoolType{},
		"apns_signing_key_id":            basetypes.StringType{},
		"apns_topic_header":              basetypes.StringType{},
		"apns_use_sandbox_endpoint":      basetypes.BoolType{},
		"created":                        basetypes.Int64Type{},
		"fcm_project_id":                 basetypes.StringType{},
		"fcm_service_account_configured": basetypes.BoolType{},
		"id":                             basetypes.StringType{},
		"modified":                       basetypes.Int64Type{},
		"name":                           basetypes.StringType{},
		"status":                         basetypes.StringType{},
		"tls_only":                       basetypes.BoolType{},
	}
}

var _ basetypes.ObjectTypable = LinksType{}

type LinksType struct {
	basetypes.ObjectType
}

func (t LinksType) Equal(o attr.Type) bool {
	other, ok := o.(LinksType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t LinksType) String() string {
	return "LinksType"
}

func (t LinksType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if diags.HasError() {
		return nil, diags
	}

	return LinksValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewLinksValueNull() LinksValue {
	return LinksValue{
		state: attr.ValueStateNull,
	}
}

func NewLinksValueUnknown() LinksValue {
	return LinksValue{
		state: attr.ValueStateUnknown,
	}
}

func NewLinksValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (LinksValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing LinksValue Attribute Value",
				"While creating a LinksValue value, a missing attribute value was detected. "+
					"A LinksValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LinksValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid LinksValue Attribute Type",
				"While creating a LinksValue value, an invalid attribute value was detected. "+
					"A LinksValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LinksValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("LinksValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra LinksValue Attribute Value",
				"While creating a LinksValue value, an extra attribute value was detected. "+
					"A LinksValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra LinksValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewLinksValueUnknown(), diags
	}

	if diags.HasError() {
		return NewLinksValueUnknown(), diags
	}

	return LinksValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewLinksValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) LinksValue {
	object, diags := NewLinksValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewLinksValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t LinksType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewLinksValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewLinksValueUnknown(), nil
	}

	if in.IsNull() {
		return NewLinksValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewLinksValueMust(LinksValue{}.AttributeTypes(ctx), attributes), nil
}

func (t LinksType) ValueType(ctx context.Context) attr.Value {
	return LinksValue{}
}

var _ basetypes.ObjectValuable = LinksValue{}

type LinksValue struct {
	state attr.ValueState
}

func (v LinksValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 0)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 0)

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v LinksValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v LinksValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v LinksValue) String() string {
	return "LinksValue"
}

func (v LinksValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{})

	return objVal, diags
}

func (v LinksValue) Equal(o attr.Value) bool {
	other, ok := o.(LinksValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	return true
}

func (v LinksValue) Type(ctx context.Context) attr.Type {
	return LinksType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v LinksValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{}
}
