package ably_control

import (
	"fmt"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/acctest"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"testing"
)

// Test Create and Update of an Ably Key with:
// Step 1: Create w/ params (app_name=autogenerated, key_name=autogenerated, capabilities.0=publish, capabilities.1=subscribe)
// Step 2: Update w/ params  (app_name=autogenerated, key_name=autogenerated, capabilities.0=history)
func TestAccAblyKey(t *testing.T) {
	app_name := acctest.RandStringFromCharSet(15, acctest.CharSetAlphaNum)
	update_app_name := "acc-test-" + app_name
	key_name := acctest.RandStringFromCharSet(15, acctest.CharSetAlphaNum)
	update_key_name := "acc-test-" + app_name
	resource.Test(t, resource.TestCase{
		PreCheck:  func() { testAccPreCheck(t) },
		Providers: testAccProviders,
		Steps: []resource.TestStep{
			// Create and Read testing of ably_app.app0
			{
				Config: testAccAblyKeyConfig(app_name, key_name, "channel100", `["publish", "subscribe"]`),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("ably_app.app0", "name", app_name),
					resource.TestCheckResourceAttr("ably_api_key.key0", "name", key_name),
					resource.TestCheckResourceAttr("ably_api_key.key0", "capabilities.channel100.0", "publish"),
					resource.TestCheckResourceAttr("ably_api_key.key0", "capabilities.channel100.1", "subscribe"),
					resource.TestCheckResourceAttrWith("ably_api_key.key0", "key", func(value string) error {
						if value == "" {
							return fmt.Errorf("key can't be empty")
						}
						return nil
					}),
				),
			},
			// Update and Read testing of ably_app.app0
			{
				Config: testAccAblyKeyConfig(update_app_name, update_key_name, "channel100", `["history"]`),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("ably_app.app0", "name", update_app_name),
					resource.TestCheckResourceAttr("ably_api_key.key0", "name", update_key_name),
					resource.TestCheckResourceAttr("ably_api_key.key0", "capabilities.channel100.0", "history"),
					resource.TestCheckResourceAttrWith("ably_api_key.key0", "key", func(value string) error {
						if value == "" {
							return fmt.Errorf("key can't be empty")
						}
						return nil
					}),
				),
			},
			// Delete testing automatically occurs in TestCase
		},
	})
}

// Function with inline HCL to provision an ably_app resource
// Takes App name, Key Name, Capability Name and Capability List as function params.
func testAccAblyKeyConfig(appName string, keyName string, keyCapabilityName0 string, keyCapabilityCap0 string) string {
	return fmt.Sprintf(`
terraform {
	required_providers {
		ably = {
		source = "github.com/ably/ably"
		}
	}
}
	
# You can provide your Ably Token & URL inline or use environment variables ABLY_ACCOUNT_TOKEN & ABLY_URL
provider "ably" {}
	  
resource "ably_app" "app0" {
	name     = %[1]q
	status   = "enabled"
	tls_only = true
}

resource "ably_api_key" "key0" {
	app_id = ably_app.app0.id
	name   = %[2]q
	capabilities = {
	  %[3]q = %[4]s
	}
  }
`, appName, keyName, keyCapabilityName0, keyCapabilityCap0)
}
