// Package provider implements the Ably provider for Terraform
package provider

import (
	"fmt"
	"regexp"
	"testing"

	control "github.com/ably/terraform-provider-ably/client"

	"github.com/hashicorp/terraform-plugin-testing/helper/acctest"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
)

var cert string = `-----BEGIN CERTIFICATE-----
MIIGGDCCBQCgAwIBAgIIN67hazCzGwwwDQYJKoZIhvcNAQELBQAwgZYxCzAJBgNV
BAYTAlVTMRMwEQYDVQQKDApBcHBsZSBJbmMuMSwwKgYDVQQLDCNBcHBsZSBXb3Js
ZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9uczFEMEIGA1UEAww7QXBwbGUgV29ybGR3
aWRlIERldmVsb3BlciBSZWxhdGlvbnMgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkw
HhcNMTcxMjE0MTMyMTQzWhcNMTkwMTEzMTMyMTQzWjCBkzEhMB8GCgmSJomT8ixk
AQEMEWlvLmFibHkucHVzaC1kZW1vMS8wLQYDVQQDDCZBcHBsZSBQdXNoIFNlcnZp
Y2VzOiBpby5hYmx5LnB1c2gtZGVtbzETMBEGA1UECwwKWFhZOThBVkRSNjEbMBkG
A1UECgwSQWJseSBSZWFsLXRpbWUgTHRkMQswCQYDVQQGEwJVUzCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAN1xIAgCXDRzRiw2lzQjRPS/RNQrLceq+qMR
cU2quAmeBL+nR68TCtwcnEYzyE7kiDRd/sFxV6gH3raCYf7YjyGVVaLmG4WfK3gh
qWeuaNap29lerkwTcRhBTdJVzvCbffO/4QuzbNkpuFv91p99FFVtlsPGBTR4THRy
iLv1fOeA+p8+wbOEeyQah7OS70AwJ4p1UPQF57rd6eR8ea/tbgvB4LAYo4qSAbSP
Uizz2boYofAlhbgVg+eJbcEDCy1Z6UOT4bv9T8Uet7GUnDcLA5W9YhAZu5gS9hrZ
HhK/p4n+QLVkvgigVgWIEAaxqniIaFslOOR1LFH9yioYZFFDM38CAwEAAaOCAmkw
ggJlMB0GA1UdDgQWBBRiwxd3NoXz1hczNuRDAzJ15Jk/ADAMBgNVHRMBAf8EAjAA
MB8GA1UdIwQYMBaAFIgnFwmpthhgi+zruvZHWcVSVKO3MIIBHAYDVR0gBIIBEzCC
AQ8wggELBgkqhkiG92NkBQEwgf0wgcMGCCsGAQUFBwICMIG2DIGzUmVsaWFuY2Ug
b24gdGhpcyBjZXJ0aWZpY2F0ZSBieSBhbnkgcGFydHkgYXNzdW1lcyBhY2NlcHRh
bmNlIG9mIHRoZSB0aGVuIGFwcGxpY2FibGUgc3RhbmRhcmQgdGVybXMgYW5kIGNv
bmRpdGlvbnMgb2YgdXNlLCBjZXJ0aWZpY2F0ZSBwb2xpY3kgYW5kIGNlcnRpZmlj
YXRpb24gcHJhY3RpY2Ugc3RhdGVtZW50cy4wNQYIKwYBBQUHAgEWKWh0dHA6Ly93
d3cuYXBwbGUuY29tL2NlcnRpZmljYXRlYXV0aG9yaXR5MDAGA1UdHwQpMCcwJaAj
oCGGH2h0dHA6Ly9jcmwuYXBwbGUuY29tL3d3ZHJjYS5jcmwwDgYDVR0PAQH/BAQD
AgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMCMBAGCiqGSIb3Y2QGAwEEAgUAMBAGCiqG
SIb3Y2QGAwIEAgUAMHoGCiqGSIb3Y2QGAwYEbDBqDBFpby5hYmx5LnB1c2gtZGVt
bzAFDANhcHAMFmlvLmFibHkucHVzaC1kZW1vLnZvaXAwBgwEdm9pcAweaW8uYWJs
eS5wdXNoLWRlbW8uY29tcGxpY2F0aW9uMA4MDGNvbXBsaWNhdGlvbjANBgkqhkiG
9w0BAQsFAAOCAQEAsir24YYCpb4/Pn76ur2kn38I1Nfe4gsxqNfkmItOYKc0H0UX
JOGBaoJTrvKGb5jaMXwsDTuUlgO1tz1tOKZk31Y1YUlmqnZvw8YOJp1GgEB/8kJF
9BNvsoJOOy0AFuW7IV67OfPCBzA9j8JoNHz+6hiHILycF0LEvR7Cs8qE0rFFJLqW
T+LHFRs+0vqDDxxriaEXbJGeRNAseUrT2O4ey41U2GaBwyuo41SFfF0jgS2fINku
OYA5r5WJTBbKHaxALnanHqDDWYRn/RXjtdDjdOby3JvFdyZul75lqBnKQ+2n6F7g
umtfr8jT+b4KanXzXe/TJ7OTrxH2nwgvKgnj9w==
-----END CERTIFICATE-----`

var key string = "-----BEGIN PRIVATE KEY-----\naaa\n-----END PRIVATE KEY-----"

// Test Create and Update of an Ably app with:
// Step 1: Create w/ params (name=autogenerated, status=enabled, tls_only=true)
// Step 2: Update w/ params (name=acc-test-{autogenerated}, status=disabled, tls_only=false)
func TestAccAblyApp(t *testing.T) {
	appName := acctest.RandStringFromCharSet(15, acctest.CharSetAlphaNum)
	updateAppName := "acc-test-" + appName

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read testing of ably_app.app0
			{
				Config: testAccAblyAppConfig(&control.AppResponse{
					Name:                   appName,
					Status:                 "enabled",
					TLSOnly:                ptr(true),
					APNSUseSandboxEndpoint: ptr(true),
				}, ptr("a"), ptr("{\"account\":\"foo\"}"), ptr("project-a"), cert, key),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("ably_app.app0", "name", appName),
					resource.TestCheckResourceAttr("ably_app.app0", "status", "enabled"),
					resource.TestCheckResourceAttr("ably_app.app0", "tls_only", "true"),
					resource.TestCheckResourceAttr("ably_app.app0", "fcm_key", "a"),
					resource.TestCheckResourceAttr("ably_app.app0", "fcm_service_account", "{\"account\":\"foo\"}"),
					resource.TestCheckResourceAttr("ably_app.app0", "fcm_project_id", "project-a"),
					resource.TestCheckResourceAttr("ably_app.app0", "apns_certificate", cert),
					resource.TestCheckResourceAttr("ably_app.app0", "apns_private_key", key),
					resource.TestCheckResourceAttr("ably_app.app0", "apns_use_sandbox_endpoint", "true"),
					resource.TestCheckResourceAttrSet("ably_app.app0", "id"),
					resource.TestCheckResourceAttrSet("ably_app.app0", "account_id"),
					resource.TestCheckResourceAttrSet("ably_app.app0", "created"),
					resource.TestCheckResourceAttrSet("ably_app.app0", "modified"),
				),
			},
			// ImportState testing of ably_app.app0
			{
				ResourceName:      "ably_app.app0",
				ImportState:       true,
				ImportStateVerify: true,
				ImportStateIdFunc: func(s *terraform.State) (string, error) {
					rs, ok := s.RootModule().Resources["ably_app.app0"]
					if !ok {
						return "", fmt.Errorf("resource not found")
					}
					return rs.Primary.ID, nil
				},
				ImportStateVerifyIgnore: []string{
					"fcm_key",
					"fcm_service_account",
					"apns_certificate",
					"apns_private_key",
				},
			},
			// Update and Read testing of ably_app.app0
			{
				Config: testAccAblyAppConfig(&control.AppResponse{
					Name:                   updateAppName,
					Status:                 "disabled",
					TLSOnly:                ptr(false),
					APNSUseSandboxEndpoint: ptr(true),
				}, ptr("b"), ptr("{\"account\":\"bar\"}"), ptr("project-b"), cert, key),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("ably_app.app0", "name", updateAppName),
					resource.TestCheckResourceAttr("ably_app.app0", "status", "disabled"),
					resource.TestCheckResourceAttr("ably_app.app0", "tls_only", "false"),
					resource.TestCheckResourceAttr("ably_app.app0", "fcm_key", "b"),
					resource.TestCheckResourceAttr("ably_app.app0", "fcm_service_account", "{\"account\":\"bar\"}"),
					resource.TestCheckResourceAttr("ably_app.app0", "fcm_project_id", "project-b"),
					resource.TestCheckResourceAttr("ably_app.app0", "apns_certificate", cert),
					resource.TestCheckResourceAttr("ably_app.app0", "apns_private_key", key),
					resource.TestCheckResourceAttr("ably_app.app0", "apns_use_sandbox_endpoint", "true"),
				),
			},
			// Delete testing automatically occurs in TestCase
		},
	})
}

// Function with inline HCL to provision an ably_app resource
// Takes AppResponse fields and sensitive string values as function params.
// Sensitive fields (fcmKey, fcmServiceAccount, fcmProjectID, apnsCertificate, apnsPrivateKey)
// are not in AppResponse, so they are passed separately.
func testAccAblyAppConfig(app *control.AppResponse, fcmKey, fcmServiceAccount, fcmProjectID *string, apnsCertificate, apnsPrivateKey string) string {
	return fmt.Sprintf(`
# You can provide your Ably Token & URL inline or use environment variables ABLY_ACCOUNT_TOKEN & ABLY_URL
terraform {
	required_providers {
		ably = {
			source = "registry.terraform.io/ably/ably"
		}
	}
}
provider "ably" {}

resource "ably_app" "app0" {
	name                      = %[1]q
	status                    = %[2]q
	tls_only                  = %[3]t
	fcm_key                   = %[4]q
	fcm_service_account       = %[5]q
	fcm_project_id            = %[6]q
	apns_certificate          = %[7]q
	apns_private_key          = %[8]q
	apns_use_sandbox_endpoint = %[9]t
}
`,
		app.Name,
		app.Status,
		deref(app.TLSOnly),
		deref(fcmKey),
		deref(fcmServiceAccount),
		deref(fcmProjectID),
		apnsCertificate,
		apnsPrivateKey,
		deref(app.APNSUseSandboxEndpoint),
	)
}

func TestAccAblyApp_InvalidConfig(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: `
terraform {
	required_providers {
		ably = {
			source = "registry.terraform.io/ably/ably"
		}
	}
}
provider "ably" {}
resource "ably_app" "app0" {
	status = "enabled"
}
`,
				ExpectError: regexp.MustCompile(`(?i).*missing.*|.*required.*`),
			},
		},
	})
}

func TestAccAblyApp_SteadyState(t *testing.T) {
	appName := acctest.RandStringFromCharSet(15, acctest.CharSetAlphaNum)
	config := fmt.Sprintf(`
terraform {
	required_providers {
		ably = {
			source = "registry.terraform.io/ably/ably"
		}
	}
}
provider "ably" {}
resource "ably_app" "app0" {
	name     = %q
	status   = "enabled"
	tls_only = true
}
`, appName)

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: config,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("ably_app.app0", "name", appName),
				),
			},
			{
				Config:   config,
				PlanOnly: true,
			},
		},
	})
}
