// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_app

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func AppResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"_links": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{},
				CustomType: LinksType{
					ObjectType: types.ObjectType{
						AttrTypes: LinksValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "A link self-referencing the app that has been created.",
				MarkdownDescription: "A link self-referencing the app that has been created.",
			},
			"account_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of your Ably account.",
				MarkdownDescription: "The ID of your Ably account.",
			},
			"apns_auth_type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The Apple Push Notification service authentication type. Use `certificate` for p12 certificate-based auth, or `token` for p8 key-based auth.",
				MarkdownDescription: "The Apple Push Notification service authentication type. Use `certificate` for p12 certificate-based auth, or `token` for p8 key-based auth.",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"certificate",
						"token",
					),
				},
			},
			"apns_certificate": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The Apple Push Notification service certificate.",
				MarkdownDescription: "The Apple Push Notification service certificate.",
			},
			"apns_certificate_configured": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether a certificate-based APNs configuration is currently active.",
				MarkdownDescription: "Whether a certificate-based APNs configuration is currently active.",
			},
			"apns_issuer_key": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The Team ID from the Apple Developer account. Used as the issuer when generating APNs authentication tokens.",
				MarkdownDescription: "The Team ID from the Apple Developer account. Used as the issuer when generating APNs authentication tokens.",
			},
			"apns_private_key": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The Apple Push Notification service private key.",
				MarkdownDescription: "The Apple Push Notification service private key.",
			},
			"apns_signing_key": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The contents of the `.p8` signing key file from the Apple Developer portal. Used for token-based APNs authentication.",
				MarkdownDescription: "The contents of the `.p8` signing key file from the Apple Developer portal. Used for token-based APNs authentication.",
			},
			"apns_signing_key_configured": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether a token-based (p8) APNs signing key is currently configured.",
				MarkdownDescription: "Whether a token-based (p8) APNs signing key is currently configured.",
			},
			"apns_signing_key_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The 10-character Key ID from the Apple Developer portal, associated with the `.p8` signing key.",
				MarkdownDescription: "The 10-character Key ID from the Apple Developer portal, associated with the `.p8` signing key.",
			},
			"apns_topic_header": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The app's bundle ID (for example, `com.example.myapp`). Used as the `apns-topic` header when sending push notifications.",
				MarkdownDescription: "The app's bundle ID (for example, `com.example.myapp`). Used as the `apns-topic` header when sending push notifications.",
			},
			"apns_use_sandbox_endpoint": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Use the Apple Push Notification service sandbox endpoint.",
				MarkdownDescription: "Use the Apple Push Notification service sandbox endpoint.",
			},
			"created": schema.Int64Attribute{
				Computed:            true,
				Description:         "Unix timestamp representing the date and time of creation of the application.",
				MarkdownDescription: "Unix timestamp representing the date and time of creation of the application.",
			},
			"fcm_key": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The Firebase Cloud Messaging key.",
				MarkdownDescription: "The Firebase Cloud Messaging key.",
			},
			"fcm_project_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The unique identifier for the Firebase Cloud Messaging(FCM) project. This ID is used to specify the Firebase project when configuring FCM or other Firebase services.",
				MarkdownDescription: "The unique identifier for the Firebase Cloud Messaging(FCM) project. This ID is used to specify the Firebase project when configuring FCM or other Firebase services.",
			},
			"fcm_service_account": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Used to specify the Firebase Cloud Messaging(FCM) service account credentials used for authentication and enabling communication with FCM to send push notifications to devices.",
				MarkdownDescription: "Used to specify the Firebase Cloud Messaging(FCM) service account credentials used for authentication and enabling communication with FCM to send push notifications to devices.",
			},
			"fcm_service_account_configured": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether Firebase Cloud Messaging (FCM) service account credentials are currently configured.",
				MarkdownDescription: "Whether Firebase Cloud Messaging (FCM) service account credentials are currently configured.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The application ID.",
				MarkdownDescription: "The application ID.",
			},
			"modified": schema.Int64Attribute{
				Computed:            true,
				Description:         "Unix timestamp representing the date and time of last modification of the application.",
				MarkdownDescription: "Unix timestamp representing the date and time of last modification of the application.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the application for your reference only.",
				MarkdownDescription: "The name of the application for your reference only.",
			},
			"parent_account_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The account ID for which to retrieve the associated applications.",
				MarkdownDescription: "The account ID for which to retrieve the associated applications.",
			},
			"status": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The status of the application. Can be `enabled` or `disabled`. Enabled means available to accept inbound connections and all services are available.",
				MarkdownDescription: "The status of the application. Can be `enabled` or `disabled`. Enabled means available to accept inbound connections and all services are available.",
				DeprecationMessage:  "This attribute is deprecated.",
			},
			"tls_only": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Enforce TLS for all connections.",
				MarkdownDescription: "Enforce TLS for all connections.",
			},
		},
	}
}

type AppModel struct {
	Links                       LinksValue   `tfsdk:"_links"`
	AccountId                   types.String `tfsdk:"account_id"`
	ApnsAuthType                types.String `tfsdk:"apns_auth_type"`
	ApnsCertificate             types.String `tfsdk:"apns_certificate"`
	ApnsCertificateConfigured   types.Bool   `tfsdk:"apns_certificate_configured"`
	ApnsIssuerKey               types.String `tfsdk:"apns_issuer_key"`
	ApnsPrivateKey              types.String `tfsdk:"apns_private_key"`
	ApnsSigningKey              types.String `tfsdk:"apns_signing_key"`
	ApnsSigningKeyConfigured    types.Bool   `tfsdk:"apns_signing_key_configured"`
	ApnsSigningKeyId            types.String `tfsdk:"apns_signing_key_id"`
	ApnsTopicHeader             types.String `tfsdk:"apns_topic_header"`
	ApnsUseSandboxEndpoint      types.Bool   `tfsdk:"apns_use_sandbox_endpoint"`
	Created                     types.Int64  `tfsdk:"created"`
	FcmKey                      types.String `tfsdk:"fcm_key"`
	FcmProjectId                types.String `tfsdk:"fcm_project_id"`
	FcmServiceAccount           types.String `tfsdk:"fcm_service_account"`
	FcmServiceAccountConfigured types.Bool   `tfsdk:"fcm_service_account_configured"`
	Id                          types.String `tfsdk:"id"`
	Modified                    types.Int64  `tfsdk:"modified"`
	Name                        types.String `tfsdk:"name"`
	ParentAccountId             types.String `tfsdk:"parent_account_id"`
	Status                      types.String `tfsdk:"status"`
	TlsOnly                     types.Bool   `tfsdk:"tls_only"`
}

var _ basetypes.ObjectTypable = LinksType{}

type LinksType struct {
	basetypes.ObjectType
}

func (t LinksType) Equal(o attr.Type) bool {
	other, ok := o.(LinksType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t LinksType) String() string {
	return "LinksType"
}

func (t LinksType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if diags.HasError() {
		return nil, diags
	}

	return LinksValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewLinksValueNull() LinksValue {
	return LinksValue{
		state: attr.ValueStateNull,
	}
}

func NewLinksValueUnknown() LinksValue {
	return LinksValue{
		state: attr.ValueStateUnknown,
	}
}

func NewLinksValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (LinksValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing LinksValue Attribute Value",
				"While creating a LinksValue value, a missing attribute value was detected. "+
					"A LinksValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LinksValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid LinksValue Attribute Type",
				"While creating a LinksValue value, an invalid attribute value was detected. "+
					"A LinksValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LinksValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("LinksValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra LinksValue Attribute Value",
				"While creating a LinksValue value, an extra attribute value was detected. "+
					"A LinksValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra LinksValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewLinksValueUnknown(), diags
	}

	if diags.HasError() {
		return NewLinksValueUnknown(), diags
	}

	return LinksValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewLinksValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) LinksValue {
	object, diags := NewLinksValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewLinksValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t LinksType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewLinksValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewLinksValueUnknown(), nil
	}

	if in.IsNull() {
		return NewLinksValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewLinksValueMust(LinksValue{}.AttributeTypes(ctx), attributes), nil
}

func (t LinksType) ValueType(ctx context.Context) attr.Value {
	return LinksValue{}
}

var _ basetypes.ObjectValuable = LinksValue{}

type LinksValue struct {
	state attr.ValueState
}

func (v LinksValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 0)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 0)

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v LinksValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v LinksValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v LinksValue) String() string {
	return "LinksValue"
}

func (v LinksValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{})

	return objVal, diags
}

func (v LinksValue) Equal(o attr.Value) bool {
	other, ok := o.(LinksValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	return true
}

func (v LinksValue) Type(ctx context.Context) attr.Type {
	return LinksType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v LinksValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{}
}
