// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_keys

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func KeysDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"app_id": schema.StringAttribute{
				Required:            true,
				Description:         "The application ID.",
				MarkdownDescription: "The application ID.",
			},
			"keys": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"app_id": schema.StringAttribute{
							Computed:            true,
							Description:         "The Ably application ID which this key is associated with.",
							MarkdownDescription: "The Ably application ID which this key is associated with.",
						},
						"capability": schema.MapAttribute{
							ElementType: types.ListType{
								ElemType: types.StringType,
							},
							Computed:            true,
							Description:         "The capabilities that this key has. More information on capabilities can be found in the Ably <a href=\"https://ably.com/docs/auth/capabilities\">capabilities docs</a>.",
							MarkdownDescription: "The capabilities that this key has. More information on capabilities can be found in the Ably <a href=\"https://ably.com/docs/auth/capabilities\">capabilities docs</a>.",
						},
						"created": schema.Int64Attribute{
							Computed:            true,
							Description:         "Unix timestamp representing the date and time of creation of the key.",
							MarkdownDescription: "Unix timestamp representing the date and time of creation of the key.",
						},
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "The key ID.",
							MarkdownDescription: "The key ID.",
						},
						"key": schema.StringAttribute{
							Computed:            true,
							Sensitive:           true,
							Description:         "The complete API key including API secret.",
							MarkdownDescription: "The complete API key including API secret.",
						},
						"modified": schema.Int64Attribute{
							Computed:            true,
							Description:         "Unix timestamp representing the date and time of the last modification of the key.",
							MarkdownDescription: "Unix timestamp representing the date and time of the last modification of the key.",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "The name for your API key. This is a friendly name for your reference.",
							MarkdownDescription: "The name for your API key. This is a friendly name for your reference.",
						},
						"revocable_tokens": schema.BoolAttribute{
							Computed:            true,
							Description:         "If `true`, tokens issued by this key can be individually revoked. See the <a href=\"https://ably.com/docs/auth/revocation\">token revocation</a> documentation for more details.",
							MarkdownDescription: "If `true`, tokens issued by this key can be individually revoked. See the <a href=\"https://ably.com/docs/auth/revocation\">token revocation</a> documentation for more details.",
						},
						"status": schema.Int64Attribute{
							Computed:            true,
							Description:         "The status of the key. `0` is enabled, `1` is revoked.",
							MarkdownDescription: "The status of the key. `0` is enabled, `1` is revoked.",
						},
					},
					CustomType: KeysType{
						ObjectType: types.ObjectType{
							AttrTypes: KeysValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type KeysModel struct {
	AppId types.String `tfsdk:"app_id"`
	Keys  types.Set    `tfsdk:"keys"`
}

var _ basetypes.ObjectTypable = KeysType{}

type KeysType struct {
	basetypes.ObjectType
}

func (t KeysType) Equal(o attr.Type) bool {
	other, ok := o.(KeysType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t KeysType) String() string {
	return "KeysType"
}

func (t KeysType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	appIdAttribute, ok := attributes["app_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`app_id is missing from object`)

		return nil, diags
	}

	appIdVal, ok := appIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`app_id expected to be basetypes.StringValue, was: %T`, appIdAttribute))
	}

	capabilityAttribute, ok := attributes["capability"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`capability is missing from object`)

		return nil, diags
	}

	capabilityVal, ok := capabilityAttribute.(basetypes.MapValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`capability expected to be basetypes.MapValue, was: %T`, capabilityAttribute))
	}

	createdAttribute, ok := attributes["created"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created is missing from object`)

		return nil, diags
	}

	createdVal, ok := createdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created expected to be basetypes.Int64Value, was: %T`, createdAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return nil, diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	modifiedAttribute, ok := attributes["modified"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`modified is missing from object`)

		return nil, diags
	}

	modifiedVal, ok := modifiedAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`modified expected to be basetypes.Int64Value, was: %T`, modifiedAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	revocableTokensAttribute, ok := attributes["revocable_tokens"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`revocable_tokens is missing from object`)

		return nil, diags
	}

	revocableTokensVal, ok := revocableTokensAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`revocable_tokens expected to be basetypes.BoolValue, was: %T`, revocableTokensAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return nil, diags
	}

	statusVal, ok := statusAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.Int64Value, was: %T`, statusAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return KeysValue{
		AppId:           appIdVal,
		Capability:      capabilityVal,
		Created:         createdVal,
		Id:              idVal,
		Key:             keyVal,
		Modified:        modifiedVal,
		Name:            nameVal,
		RevocableTokens: revocableTokensVal,
		Status:          statusVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewKeysValueNull() KeysValue {
	return KeysValue{
		state: attr.ValueStateNull,
	}
}

func NewKeysValueUnknown() KeysValue {
	return KeysValue{
		state: attr.ValueStateUnknown,
	}
}

func NewKeysValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (KeysValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing KeysValue Attribute Value",
				"While creating a KeysValue value, a missing attribute value was detected. "+
					"A KeysValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("KeysValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid KeysValue Attribute Type",
				"While creating a KeysValue value, an invalid attribute value was detected. "+
					"A KeysValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("KeysValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("KeysValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra KeysValue Attribute Value",
				"While creating a KeysValue value, an extra attribute value was detected. "+
					"A KeysValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra KeysValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewKeysValueUnknown(), diags
	}

	appIdAttribute, ok := attributes["app_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`app_id is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	appIdVal, ok := appIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`app_id expected to be basetypes.StringValue, was: %T`, appIdAttribute))
	}

	capabilityAttribute, ok := attributes["capability"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`capability is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	capabilityVal, ok := capabilityAttribute.(basetypes.MapValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`capability expected to be basetypes.MapValue, was: %T`, capabilityAttribute))
	}

	createdAttribute, ok := attributes["created"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	createdVal, ok := createdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created expected to be basetypes.Int64Value, was: %T`, createdAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	modifiedAttribute, ok := attributes["modified"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`modified is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	modifiedVal, ok := modifiedAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`modified expected to be basetypes.Int64Value, was: %T`, modifiedAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	revocableTokensAttribute, ok := attributes["revocable_tokens"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`revocable_tokens is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	revocableTokensVal, ok := revocableTokensAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`revocable_tokens expected to be basetypes.BoolValue, was: %T`, revocableTokensAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	statusVal, ok := statusAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.Int64Value, was: %T`, statusAttribute))
	}

	if diags.HasError() {
		return NewKeysValueUnknown(), diags
	}

	return KeysValue{
		AppId:           appIdVal,
		Capability:      capabilityVal,
		Created:         createdVal,
		Id:              idVal,
		Key:             keyVal,
		Modified:        modifiedVal,
		Name:            nameVal,
		RevocableTokens: revocableTokensVal,
		Status:          statusVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewKeysValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) KeysValue {
	object, diags := NewKeysValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewKeysValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t KeysType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewKeysValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewKeysValueUnknown(), nil
	}

	if in.IsNull() {
		return NewKeysValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewKeysValueMust(KeysValue{}.AttributeTypes(ctx), attributes), nil
}

func (t KeysType) ValueType(ctx context.Context) attr.Value {
	return KeysValue{}
}

var _ basetypes.ObjectValuable = KeysValue{}

type KeysValue struct {
	AppId           basetypes.StringValue `tfsdk:"app_id"`
	Capability      basetypes.MapValue    `tfsdk:"capability"`
	Created         basetypes.Int64Value  `tfsdk:"created"`
	Id              basetypes.StringValue `tfsdk:"id"`
	Key             basetypes.StringValue `tfsdk:"key"`
	Modified        basetypes.Int64Value  `tfsdk:"modified"`
	Name            basetypes.StringValue `tfsdk:"name"`
	RevocableTokens basetypes.BoolValue   `tfsdk:"revocable_tokens"`
	Status          basetypes.Int64Value  `tfsdk:"status"`
	state           attr.ValueState
}

func (v KeysValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 9)

	var val tftypes.Value
	var err error

	attrTypes["app_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["capability"] = basetypes.MapType{
		ElemType: types.ListType{
			ElemType: types.StringType,
		},
	}.TerraformType(ctx)
	attrTypes["created"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["key"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["modified"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["revocable_tokens"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["status"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 9)

		val, err = v.AppId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["app_id"] = val

		val, err = v.Capability.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["capability"] = val

		val, err = v.Created.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Key.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key"] = val

		val, err = v.Modified.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["modified"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.RevocableTokens.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["revocable_tokens"] = val

		val, err = v.Status.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v KeysValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v KeysValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v KeysValue) String() string {
	return "KeysValue"
}

func (v KeysValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var capabilityVal basetypes.MapValue
	switch {
	case v.Capability.IsUnknown():
		capabilityVal = types.MapUnknown(types.ListType{
			ElemType: types.StringType,
		})
	case v.Capability.IsNull():
		capabilityVal = types.MapNull(types.ListType{
			ElemType: types.StringType,
		})
	default:
		var d diag.Diagnostics
		capabilityVal, d = types.MapValue(types.ListType{
			ElemType: types.StringType,
		}, v.Capability.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"app_id": basetypes.StringType{},
			"capability": basetypes.MapType{
				ElemType: types.ListType{
					ElemType: types.StringType,
				},
			},
			"created":          basetypes.Int64Type{},
			"id":               basetypes.StringType{},
			"key":              basetypes.StringType{},
			"modified":         basetypes.Int64Type{},
			"name":             basetypes.StringType{},
			"revocable_tokens": basetypes.BoolType{},
			"status":           basetypes.Int64Type{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"app_id": basetypes.StringType{},
		"capability": basetypes.MapType{
			ElemType: types.ListType{
				ElemType: types.StringType,
			},
		},
		"created":          basetypes.Int64Type{},
		"id":               basetypes.StringType{},
		"key":              basetypes.StringType{},
		"modified":         basetypes.Int64Type{},
		"name":             basetypes.StringType{},
		"revocable_tokens": basetypes.BoolType{},
		"status":           basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"app_id":           v.AppId,
			"capability":       capabilityVal,
			"created":          v.Created,
			"id":               v.Id,
			"key":              v.Key,
			"modified":         v.Modified,
			"name":             v.Name,
			"revocable_tokens": v.RevocableTokens,
			"status":           v.Status,
		})

	return objVal, diags
}

func (v KeysValue) Equal(o attr.Value) bool {
	other, ok := o.(KeysValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AppId.Equal(other.AppId) {
		return false
	}

	if !v.Capability.Equal(other.Capability) {
		return false
	}

	if !v.Created.Equal(other.Created) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Key.Equal(other.Key) {
		return false
	}

	if !v.Modified.Equal(other.Modified) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.RevocableTokens.Equal(other.RevocableTokens) {
		return false
	}

	if !v.Status.Equal(other.Status) {
		return false
	}

	return true
}

func (v KeysValue) Type(ctx context.Context) attr.Type {
	return KeysType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v KeysValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"app_id": basetypes.StringType{},
		"capability": basetypes.MapType{
			ElemType: types.ListType{
				ElemType: types.StringType,
			},
		},
		"created":          basetypes.Int64Type{},
		"id":               basetypes.StringType{},
		"key":              basetypes.StringType{},
		"modified":         basetypes.Int64Type{},
		"name":             basetypes.StringType{},
		"revocable_tokens": basetypes.BoolType{},
		"status":           basetypes.Int64Type{},
	}
}
