// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_me

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func MeDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"account": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "The account ID.",
						MarkdownDescription: "The account ID.",
					},
					"name": schema.StringAttribute{
						Computed:            true,
						Description:         "The name of the account.",
						MarkdownDescription: "The name of the account.",
					},
				},
				CustomType: AccountType{
					ObjectType: types.ObjectType{
						AttrTypes: AccountValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"token": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"capabilities": schema.ListAttribute{
						ElementType:         types.StringType,
						Computed:            true,
						Description:         "An array containing the access capabilities associated with the access token.",
						MarkdownDescription: "An array containing the access capabilities associated with the access token.",
					},
					"expires_at": schema.StringAttribute{
						Computed:            true,
						Description:         "The date and time at which the access token expires, in ISO 8601 format. A value of `null` indicates the token does not expire.",
						MarkdownDescription: "The date and time at which the access token expires, in ISO 8601 format. A value of `null` indicates the token does not expire.",
					},
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "The token ID.",
						MarkdownDescription: "The token ID.",
					},
					"last_used_at": schema.StringAttribute{
						Computed:            true,
						Description:         "The date and time at which the access token was last used to authenticate a Control API request, in ISO 8601 format. Updated at most once per 10-minute window. A value of `null` indicates the token has not been used since tracking began.",
						MarkdownDescription: "The date and time at which the access token was last used to authenticate a Control API request, in ISO 8601 format. Updated at most once per 10-minute window. A value of `null` indicates the token has not been used since tracking began.",
					},
					"name": schema.StringAttribute{
						Computed:            true,
						Description:         "The friendly name for the token.",
						MarkdownDescription: "The friendly name for the token.",
					},
				},
				CustomType: TokenType{
					ObjectType: types.ObjectType{
						AttrTypes: TokenValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"user": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"email": schema.StringAttribute{
						Computed:            true,
						Description:         "Email address of the user associated with the account.",
						MarkdownDescription: "Email address of the user associated with the account.",
					},
					"id": schema.Int64Attribute{
						Computed:            true,
						Description:         "The user ID associated with the account.",
						MarkdownDescription: "The user ID associated with the account.",
					},
				},
				CustomType: UserType{
					ObjectType: types.ObjectType{
						AttrTypes: UserValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
		},
	}
}

type MeModel struct {
	Account AccountValue `tfsdk:"account"`
	Token   TokenValue   `tfsdk:"token"`
	User    UserValue    `tfsdk:"user"`
}

var _ basetypes.ObjectTypable = AccountType{}

type AccountType struct {
	basetypes.ObjectType
}

func (t AccountType) Equal(o attr.Type) bool {
	other, ok := o.(AccountType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AccountType) String() string {
	return "AccountType"
}

func (t AccountType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AccountValue{
		Id:    idVal,
		Name:  nameVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewAccountValueNull() AccountValue {
	return AccountValue{
		state: attr.ValueStateNull,
	}
}

func NewAccountValueUnknown() AccountValue {
	return AccountValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAccountValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AccountValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AccountValue Attribute Value",
				"While creating a AccountValue value, a missing attribute value was detected. "+
					"A AccountValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AccountValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AccountValue Attribute Type",
				"While creating a AccountValue value, an invalid attribute value was detected. "+
					"A AccountValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AccountValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AccountValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AccountValue Attribute Value",
				"While creating a AccountValue value, an extra attribute value was detected. "+
					"A AccountValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AccountValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAccountValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewAccountValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewAccountValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return NewAccountValueUnknown(), diags
	}

	return AccountValue{
		Id:    idVal,
		Name:  nameVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewAccountValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AccountValue {
	object, diags := NewAccountValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAccountValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AccountType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAccountValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAccountValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAccountValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAccountValueMust(AccountValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AccountType) ValueType(ctx context.Context) attr.Value {
	return AccountValue{}
}

var _ basetypes.ObjectValuable = AccountValue{}

type AccountValue struct {
	Id    basetypes.StringValue `tfsdk:"id"`
	Name  basetypes.StringValue `tfsdk:"name"`
	state attr.ValueState
}

func (v AccountValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AccountValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AccountValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AccountValue) String() string {
	return "AccountValue"
}

func (v AccountValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"name": v.Name,
		})

	return objVal, diags
}

func (v AccountValue) Equal(o attr.Value) bool {
	other, ok := o.(AccountValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	return true
}

func (v AccountValue) Type(ctx context.Context) attr.Type {
	return AccountType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AccountValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = TokenType{}

type TokenType struct {
	basetypes.ObjectType
}

func (t TokenType) Equal(o attr.Type) bool {
	other, ok := o.(TokenType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TokenType) String() string {
	return "TokenType"
}

func (t TokenType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	capabilitiesAttribute, ok := attributes["capabilities"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`capabilities is missing from object`)

		return nil, diags
	}

	capabilitiesVal, ok := capabilitiesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`capabilities expected to be basetypes.ListValue, was: %T`, capabilitiesAttribute))
	}

	expiresAtAttribute, ok := attributes["expires_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`expires_at is missing from object`)

		return nil, diags
	}

	expiresAtVal, ok := expiresAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`expires_at expected to be basetypes.StringValue, was: %T`, expiresAtAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	lastUsedAtAttribute, ok := attributes["last_used_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_used_at is missing from object`)

		return nil, diags
	}

	lastUsedAtVal, ok := lastUsedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_used_at expected to be basetypes.StringValue, was: %T`, lastUsedAtAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TokenValue{
		Capabilities: capabilitiesVal,
		ExpiresAt:    expiresAtVal,
		Id:           idVal,
		LastUsedAt:   lastUsedAtVal,
		Name:         nameVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewTokenValueNull() TokenValue {
	return TokenValue{
		state: attr.ValueStateNull,
	}
}

func NewTokenValueUnknown() TokenValue {
	return TokenValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTokenValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TokenValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TokenValue Attribute Value",
				"While creating a TokenValue value, a missing attribute value was detected. "+
					"A TokenValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TokenValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TokenValue Attribute Type",
				"While creating a TokenValue value, an invalid attribute value was detected. "+
					"A TokenValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TokenValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TokenValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TokenValue Attribute Value",
				"While creating a TokenValue value, an extra attribute value was detected. "+
					"A TokenValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TokenValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTokenValueUnknown(), diags
	}

	capabilitiesAttribute, ok := attributes["capabilities"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`capabilities is missing from object`)

		return NewTokenValueUnknown(), diags
	}

	capabilitiesVal, ok := capabilitiesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`capabilities expected to be basetypes.ListValue, was: %T`, capabilitiesAttribute))
	}

	expiresAtAttribute, ok := attributes["expires_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`expires_at is missing from object`)

		return NewTokenValueUnknown(), diags
	}

	expiresAtVal, ok := expiresAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`expires_at expected to be basetypes.StringValue, was: %T`, expiresAtAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewTokenValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	lastUsedAtAttribute, ok := attributes["last_used_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_used_at is missing from object`)

		return NewTokenValueUnknown(), diags
	}

	lastUsedAtVal, ok := lastUsedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_used_at expected to be basetypes.StringValue, was: %T`, lastUsedAtAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewTokenValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return NewTokenValueUnknown(), diags
	}

	return TokenValue{
		Capabilities: capabilitiesVal,
		ExpiresAt:    expiresAtVal,
		Id:           idVal,
		LastUsedAt:   lastUsedAtVal,
		Name:         nameVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewTokenValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TokenValue {
	object, diags := NewTokenValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTokenValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TokenType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTokenValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTokenValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTokenValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTokenValueMust(TokenValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TokenType) ValueType(ctx context.Context) attr.Value {
	return TokenValue{}
}

var _ basetypes.ObjectValuable = TokenValue{}

type TokenValue struct {
	Capabilities basetypes.ListValue   `tfsdk:"capabilities"`
	ExpiresAt    basetypes.StringValue `tfsdk:"expires_at"`
	Id           basetypes.StringValue `tfsdk:"id"`
	LastUsedAt   basetypes.StringValue `tfsdk:"last_used_at"`
	Name         basetypes.StringValue `tfsdk:"name"`
	state        attr.ValueState
}

func (v TokenValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["capabilities"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["expires_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["last_used_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.Capabilities.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["capabilities"] = val

		val, err = v.ExpiresAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["expires_at"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.LastUsedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["last_used_at"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TokenValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TokenValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TokenValue) String() string {
	return "TokenValue"
}

func (v TokenValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var capabilitiesVal basetypes.ListValue
	switch {
	case v.Capabilities.IsUnknown():
		capabilitiesVal = types.ListUnknown(types.StringType)
	case v.Capabilities.IsNull():
		capabilitiesVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		capabilitiesVal, d = types.ListValue(types.StringType, v.Capabilities.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"capabilities": basetypes.ListType{
				ElemType: types.StringType,
			},
			"expires_at":   basetypes.StringType{},
			"id":           basetypes.StringType{},
			"last_used_at": basetypes.StringType{},
			"name":         basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"capabilities": basetypes.ListType{
			ElemType: types.StringType,
		},
		"expires_at":   basetypes.StringType{},
		"id":           basetypes.StringType{},
		"last_used_at": basetypes.StringType{},
		"name":         basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"capabilities": capabilitiesVal,
			"expires_at":   v.ExpiresAt,
			"id":           v.Id,
			"last_used_at": v.LastUsedAt,
			"name":         v.Name,
		})

	return objVal, diags
}

func (v TokenValue) Equal(o attr.Value) bool {
	other, ok := o.(TokenValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Capabilities.Equal(other.Capabilities) {
		return false
	}

	if !v.ExpiresAt.Equal(other.ExpiresAt) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.LastUsedAt.Equal(other.LastUsedAt) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	return true
}

func (v TokenValue) Type(ctx context.Context) attr.Type {
	return TokenType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TokenValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"capabilities": basetypes.ListType{
			ElemType: types.StringType,
		},
		"expires_at":   basetypes.StringType{},
		"id":           basetypes.StringType{},
		"last_used_at": basetypes.StringType{},
		"name":         basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = UserType{}

type UserType struct {
	basetypes.ObjectType
}

func (t UserType) Equal(o attr.Type) bool {
	other, ok := o.(UserType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t UserType) String() string {
	return "UserType"
}

func (t UserType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return nil, diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return UserValue{
		Email: emailVal,
		Id:    idVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewUserValueNull() UserValue {
	return UserValue{
		state: attr.ValueStateNull,
	}
}

func NewUserValueUnknown() UserValue {
	return UserValue{
		state: attr.ValueStateUnknown,
	}
}

func NewUserValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (UserValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing UserValue Attribute Value",
				"While creating a UserValue value, a missing attribute value was detected. "+
					"A UserValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UserValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid UserValue Attribute Type",
				"While creating a UserValue value, an invalid attribute value was detected. "+
					"A UserValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UserValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("UserValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra UserValue Attribute Value",
				"While creating a UserValue value, an extra attribute value was detected. "+
					"A UserValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra UserValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewUserValueUnknown(), diags
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return NewUserValueUnknown(), diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewUserValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	if diags.HasError() {
		return NewUserValueUnknown(), diags
	}

	return UserValue{
		Email: emailVal,
		Id:    idVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewUserValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) UserValue {
	object, diags := NewUserValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewUserValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t UserType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewUserValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewUserValueUnknown(), nil
	}

	if in.IsNull() {
		return NewUserValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewUserValueMust(UserValue{}.AttributeTypes(ctx), attributes), nil
}

func (t UserType) ValueType(ctx context.Context) attr.Value {
	return UserValue{}
}

var _ basetypes.ObjectValuable = UserValue{}

type UserValue struct {
	Email basetypes.StringValue `tfsdk:"email"`
	Id    basetypes.Int64Value  `tfsdk:"id"`
	state attr.ValueState
}

func (v UserValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["email"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Email.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["email"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v UserValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v UserValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v UserValue) String() string {
	return "UserValue"
}

func (v UserValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"email": basetypes.StringType{},
		"id":    basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"email": v.Email,
			"id":    v.Id,
		})

	return objVal, diags
}

func (v UserValue) Equal(o attr.Value) bool {
	other, ok := o.(UserValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Email.Equal(other.Email) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	return true
}

func (v UserValue) Type(ctx context.Context) attr.Type {
	return UserType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v UserValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"email": basetypes.StringType{},
		"id":    basetypes.Int64Type{},
	}
}
