// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_namespace

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func NamespaceResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"app_id": schema.StringAttribute{
				Computed: true,
			},
			"authenticated": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(false),
			},
			"batching_enabled": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(false),
			},
			"batching_interval": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"conflation_enabled": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(false),
			},
			"conflation_interval": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"conflation_key": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"created": schema.Int64Attribute{
				Computed: true,
			},
			"expose_timeserial": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(false),
			},
			"id": schema.StringAttribute{
				Required: true,
			},
			"modified": schema.Int64Attribute{
				Computed: true,
			},
			"mutable_messages": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(false),
			},
			"parent_app_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"persist_last": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(false),
			},
			"persisted": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(false),
			},
			"populate_channel_registry": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(false),
			},
			"push_enabled": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(false),
			},
			"tls_only": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(false),
			},
		},
	}
}

type NamespaceModel struct {
	AppId                   types.String `tfsdk:"app_id"`
	Authenticated           types.Bool   `tfsdk:"authenticated"`
	BatchingEnabled         types.Bool   `tfsdk:"batching_enabled"`
	BatchingInterval        types.Int64  `tfsdk:"batching_interval"`
	ConflationEnabled       types.Bool   `tfsdk:"conflation_enabled"`
	ConflationInterval      types.Int64  `tfsdk:"conflation_interval"`
	ConflationKey           types.String `tfsdk:"conflation_key"`
	Created                 types.Int64  `tfsdk:"created"`
	ExposeTimeserial        types.Bool   `tfsdk:"expose_timeserial"`
	Id                      types.String `tfsdk:"id"`
	Modified                types.Int64  `tfsdk:"modified"`
	MutableMessages         types.Bool   `tfsdk:"mutable_messages"`
	ParentAppId             types.String `tfsdk:"parent_app_id"`
	PersistLast             types.Bool   `tfsdk:"persist_last"`
	Persisted               types.Bool   `tfsdk:"persisted"`
	PopulateChannelRegistry types.Bool   `tfsdk:"populate_channel_registry"`
	PushEnabled             types.Bool   `tfsdk:"push_enabled"`
	TlsOnly                 types.Bool   `tfsdk:"tls_only"`
}
