// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_namespace

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func NamespaceResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"app_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the application the namespace belongs to.",
				MarkdownDescription: "The ID of the application the namespace belongs to.",
			},
			"authenticated": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If `true`, clients will not be permitted to use (including to attach, publish, or subscribe) any channels within this namespace unless they are identified, that is, authenticated using a client ID. See the documentation for <a href=\"https://ably.com/docs/auth/identified-clients\">identified clients</a> for more details.",
				MarkdownDescription: "If `true`, clients will not be permitted to use (including to attach, publish, or subscribe) any channels within this namespace unless they are identified, that is, authenticated using a client ID. See the documentation for <a href=\"https://ably.com/docs/auth/identified-clients\">identified clients</a> for more details.",
				Default:             booldefault.StaticBool(false),
			},
			"batching_enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If `true`, channels within this namespace will start batching inbound messages instead of sending them out immediately to subscribers.",
				MarkdownDescription: "If `true`, channels within this namespace will start batching inbound messages instead of sending them out immediately to subscribers.",
				Default:             booldefault.StaticBool(false),
			},
			"batching_interval": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "If `true`, the batching interval, configurable from 20ms to 1s, temporarily holds and aggregates incoming messages. These messages are then combined and delivered as a single batch once the interval elapses or a size limit is reached (before the interval elapses).",
				MarkdownDescription: "If `true`, the batching interval, configurable from 20ms to 1s, temporarily holds and aggregates incoming messages. These messages are then combined and delivered as a single batch once the interval elapses or a size limit is reached (before the interval elapses).",
				Default:             int64default.StaticInt64(20),
			},
			"conflation_enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If `true`, enables <a href=\"https://ably.com/docs/messages#conflation\">conflation</a> for channels within this namespace. Conflation will aggregate published messages for a set period of time and evaluate them against a conflation key. Only the most recent message that satisfies the key will be sent to subscribers at the end of the conflation interval.",
				MarkdownDescription: "If `true`, enables <a href=\"https://ably.com/docs/messages#conflation\">conflation</a> for channels within this namespace. Conflation will aggregate published messages for a set period of time and evaluate them against a conflation key. Only the most recent message that satisfies the key will be sent to subscribers at the end of the conflation interval.",
				Default:             booldefault.StaticBool(false),
			},
			"conflation_interval": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The interval in milliseconds over which messages are held and evaluated for conflation.",
				MarkdownDescription: "The interval in milliseconds over which messages are held and evaluated for conflation.",
			},
			"conflation_key": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The <a href=\"https://ably.com/docs/messages#routing\">key</a> used to determine which messages should be conflated.",
				MarkdownDescription: "The <a href=\"https://ably.com/docs/messages#routing\">key</a> used to determine which messages should be conflated.",
			},
			"created": schema.Int64Attribute{
				Computed:            true,
				Description:         "Unix timestamp representing the date and time of creation of the namespace.",
				MarkdownDescription: "Unix timestamp representing the date and time of creation of the namespace.",
			},
			"expose_timeserial": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If `true`, messages received on a channel will contain a unique `timeserial` that can be referenced by later messages for use with message interactions.",
				MarkdownDescription: "If `true`, messages received on a channel will contain a unique `timeserial` that can be referenced by later messages for use with message interactions.",
				Default:             booldefault.StaticBool(false),
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "The namespace or channel name that the channel rule will apply to. For example, if you specify `namespace` the namespace will be set to `namespace` and will match with channels `namespace:*` and `namespace`.",
				MarkdownDescription: "The namespace or channel name that the channel rule will apply to. For example, if you specify `namespace` the namespace will be set to `namespace` and will match with channels `namespace:*` and `namespace`.",
			},
			"modified": schema.Int64Attribute{
				Computed:            true,
				Description:         "Unix timestamp representing the date and time of last modification of the namespace.",
				MarkdownDescription: "Unix timestamp representing the date and time of last modification of the namespace.",
			},
			"mutable_messages": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If `true`, messages published on channels within this namespace can be updated or deleted after publishing. See the <a href=\"https://ably.com/docs/messages#update\">message interactions</a> documentation for more details.",
				MarkdownDescription: "If `true`, messages published on channels within this namespace can be updated or deleted after publishing. See the <a href=\"https://ably.com/docs/messages#update\">message interactions</a> documentation for more details.",
				Default:             booldefault.StaticBool(false),
			},
			"parent_app_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The application ID.",
				MarkdownDescription: "The application ID.",
			},
			"persist_last": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If `true`, the last message published on a channel will be stored for 365 days. You can access the stored message only by using the channel rewind mechanism and attaching with rewind=1. Please note that for each message stored, an additional message is deducted from your monthly allocation.",
				MarkdownDescription: "If `true`, the last message published on a channel will be stored for 365 days. You can access the stored message only by using the channel rewind mechanism and attaching with rewind=1. Please note that for each message stored, an additional message is deducted from your monthly allocation.",
				Default:             booldefault.StaticBool(false),
			},
			"persisted": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If `true`, all messages on a channel will be stored for 24 hours. You can access stored messages via the History API. Please note that for each message stored, an additional message is deducted from your monthly allocation.",
				MarkdownDescription: "If `true`, all messages on a channel will be stored for 24 hours. You can access stored messages via the History API. Please note that for each message stored, an additional message is deducted from your monthly allocation.",
				Default:             booldefault.StaticBool(false),
			},
			"populate_channel_registry": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If `true`, channels within this namespace are included in the channel registry, enabling channel enumeration via the <a href=\"https://ably.com/docs/metadata-stats/metadata/subscribe#channel-lifecycle\">Channel Metadata API</a>.",
				MarkdownDescription: "If `true`, channels within this namespace are included in the channel registry, enabling channel enumeration via the <a href=\"https://ably.com/docs/metadata-stats/metadata/subscribe#channel-lifecycle\">Channel Metadata API</a>.",
				Default:             booldefault.StaticBool(false),
			},
			"push_enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If `true`, publishing messages with a push payload in the extras field is permitted and can trigger the delivery of a native push notification to registered devices for the channel.",
				MarkdownDescription: "If `true`, publishing messages with a push payload in the extras field is permitted and can trigger the delivery of a native push notification to registered devices for the channel.",
				Default:             booldefault.StaticBool(false),
			},
			"tls_only": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If `true`, only clients that are connected using TLS will be permitted to subscribe to any channels within this namespace.",
				MarkdownDescription: "If `true`, only clients that are connected using TLS will be permitted to subscribe to any channels within this namespace.",
				Default:             booldefault.StaticBool(false),
			},
		},
	}
}

type NamespaceModel struct {
	AppId                   types.String `tfsdk:"app_id"`
	Authenticated           types.Bool   `tfsdk:"authenticated"`
	BatchingEnabled         types.Bool   `tfsdk:"batching_enabled"`
	BatchingInterval        types.Int64  `tfsdk:"batching_interval"`
	ConflationEnabled       types.Bool   `tfsdk:"conflation_enabled"`
	ConflationInterval      types.Int64  `tfsdk:"conflation_interval"`
	ConflationKey           types.String `tfsdk:"conflation_key"`
	Created                 types.Int64  `tfsdk:"created"`
	ExposeTimeserial        types.Bool   `tfsdk:"expose_timeserial"`
	Id                      types.String `tfsdk:"id"`
	Modified                types.Int64  `tfsdk:"modified"`
	MutableMessages         types.Bool   `tfsdk:"mutable_messages"`
	ParentAppId             types.String `tfsdk:"parent_app_id"`
	PersistLast             types.Bool   `tfsdk:"persist_last"`
	Persisted               types.Bool   `tfsdk:"persisted"`
	PopulateChannelRegistry types.Bool   `tfsdk:"populate_channel_registry"`
	PushEnabled             types.Bool   `tfsdk:"push_enabled"`
	TlsOnly                 types.Bool   `tfsdk:"tls_only"`
}
