// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_rule_hive_dashboard

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func RuleHiveDashboardResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"app_id": schema.StringAttribute{
				Required:            true,
				Description:         "The Ably application ID.",
				MarkdownDescription: "The Ably application ID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"chat_room_filter": schema.StringAttribute{
				Optional:            true,
				Description:         "A regular expression that filters messages based on the chat room ID. Only messages matching this pattern will trigger the rule.",
				MarkdownDescription: "A regular expression that filters messages based on the chat room ID. Only messages matching this pattern will trigger the rule.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^/.*/$"), "must match the pattern ^/.*/$"),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The rule ID.",
				MarkdownDescription: "The rule ID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"invocation_mode": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The invocation mode for this rule. After-publish rules are invoked after a message is published.",
				MarkdownDescription: "The invocation mode for this rule. After-publish rules are invoked after a message is published.",
				Validators: []validator.String{
					stringvalidator.OneOf("AFTER_PUBLISH"),
				},
				Default: stringdefault.StaticString("AFTER_PUBLISH"),
			},
			"status": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The status of the rule. Rules can be enabled or disabled.",
				MarkdownDescription: "The status of the rule. Rules can be enabled or disabled.",
				Validators: []validator.String{
					stringvalidator.OneOf("enabled", "disabled"),
				},
				Default: stringdefault.StaticString("enabled"),
			},
			"target": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"api_key": schema.StringAttribute{
						Required:            true,
						Sensitive:           true,
						Description:         "The Hive API key for authenticating with the moderation dashboard.",
						MarkdownDescription: "The Hive API key for authenticating with the moderation dashboard.",
					},
					"check_watch_lists": schema.BoolAttribute{
						Optional:            true,
						Description:         "If `true`, messages will also be checked against Hive watch lists.",
						MarkdownDescription: "If `true`, messages will also be checked against Hive watch lists.",
					},
				},
				CustomType: TargetType{
					ObjectType: types.ObjectType{
						AttrTypes: TargetValue{}.AttributeTypes(ctx),
					},
				},
				Required:            true,
				Description:         "The target for the rule, specifying the Hive dashboard configuration.",
				MarkdownDescription: "The target for the rule, specifying the Hive dashboard configuration.",
			},
		},
	}
}

type RuleHiveDashboardModel struct {
	AppId          types.String `tfsdk:"app_id"`
	ChatRoomFilter types.String `tfsdk:"chat_room_filter"`
	Id             types.String `tfsdk:"id"`
	InvocationMode types.String `tfsdk:"invocation_mode"`
	Status         types.String `tfsdk:"status"`
	Target         TargetValue  `tfsdk:"target"`
}

var _ basetypes.ObjectTypable = TargetType{}

type TargetType struct {
	basetypes.ObjectType
}

func (t TargetType) Equal(o attr.Type) bool {
	other, ok := o.(TargetType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TargetType) String() string {
	return "TargetType"
}

func (t TargetType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	apiKeyAttribute, ok := attributes["api_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`api_key is missing from object`)

		return nil, diags
	}

	apiKeyVal, ok := apiKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`api_key expected to be basetypes.StringValue, was: %T`, apiKeyAttribute))
	}

	checkWatchListsAttribute, ok := attributes["check_watch_lists"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`check_watch_lists is missing from object`)

		return nil, diags
	}

	checkWatchListsVal, ok := checkWatchListsAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`check_watch_lists expected to be basetypes.BoolValue, was: %T`, checkWatchListsAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TargetValue{
		ApiKey:          apiKeyVal,
		CheckWatchLists: checkWatchListsVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewTargetValueNull() TargetValue {
	return TargetValue{
		state: attr.ValueStateNull,
	}
}

func NewTargetValueUnknown() TargetValue {
	return TargetValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTargetValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TargetValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TargetValue Attribute Value",
				"While creating a TargetValue value, a missing attribute value was detected. "+
					"A TargetValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TargetValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TargetValue Attribute Type",
				"While creating a TargetValue value, an invalid attribute value was detected. "+
					"A TargetValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TargetValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TargetValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TargetValue Attribute Value",
				"While creating a TargetValue value, an extra attribute value was detected. "+
					"A TargetValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TargetValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTargetValueUnknown(), diags
	}

	apiKeyAttribute, ok := attributes["api_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`api_key is missing from object`)

		return NewTargetValueUnknown(), diags
	}

	apiKeyVal, ok := apiKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`api_key expected to be basetypes.StringValue, was: %T`, apiKeyAttribute))
	}

	checkWatchListsAttribute, ok := attributes["check_watch_lists"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`check_watch_lists is missing from object`)

		return NewTargetValueUnknown(), diags
	}

	checkWatchListsVal, ok := checkWatchListsAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`check_watch_lists expected to be basetypes.BoolValue, was: %T`, checkWatchListsAttribute))
	}

	if diags.HasError() {
		return NewTargetValueUnknown(), diags
	}

	return TargetValue{
		ApiKey:          apiKeyVal,
		CheckWatchLists: checkWatchListsVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewTargetValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TargetValue {
	object, diags := NewTargetValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTargetValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TargetType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTargetValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTargetValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTargetValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTargetValueMust(TargetValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TargetType) ValueType(ctx context.Context) attr.Value {
	return TargetValue{}
}

var _ basetypes.ObjectValuable = TargetValue{}

type TargetValue struct {
	ApiKey          basetypes.StringValue `tfsdk:"api_key"`
	CheckWatchLists basetypes.BoolValue   `tfsdk:"check_watch_lists"`
	state           attr.ValueState
}

func (v TargetValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["api_key"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["check_watch_lists"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.ApiKey.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["api_key"] = val

		val, err = v.CheckWatchLists.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["check_watch_lists"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TargetValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TargetValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TargetValue) String() string {
	return "TargetValue"
}

func (v TargetValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"api_key":           basetypes.StringType{},
		"check_watch_lists": basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"api_key":           v.ApiKey,
			"check_watch_lists": v.CheckWatchLists,
		})

	return objVal, diags
}

func (v TargetValue) Equal(o attr.Value) bool {
	other, ok := o.(TargetValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ApiKey.Equal(other.ApiKey) {
		return false
	}

	if !v.CheckWatchLists.Equal(other.CheckWatchLists) {
		return false
	}

	return true
}

func (v TargetValue) Type(ctx context.Context) attr.Type {
	return TargetType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TargetValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"api_key":           basetypes.StringType{},
		"check_watch_lists": basetypes.BoolType{},
	}
}
