# Based upon:
#   https://github.com/actions/starter-workflows/blob/main/ci/go.yml

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.23, 1.24]

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          submodules: 'recursive'
          persist-credentials: false

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Download Packages
        run: go get -t -v

      - name: Format
        run: if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Vet
        run: go vet

      - name: Build
        run: |
          mkdir bin
          go build -v -o bin

      - name: Test
        run: |
          echo "provider_installation { dev_overrides { \"registry.terraform.io/ably/ably\" = \"$PWD/bin\", } direct {} }" > ~/.terraformrc
          TF_ACC=1 go test -v -parallel 4 ./...
        env:
          ABLY_ACCOUNT_TOKEN: ${{ secrets.ABLY_ACCOUNT_TOKEN }}
          ABLY_URL: 'https://staging-control.ably-dev.net/v1'
