---
page_title: "ably_rule_ifttt Resource - terraform-provider-ably"
subcategory: ""
description: |-
  The ably_rule_ifttt resource allows you to create and manage an Ably integration rule for IFTTT. Read more at https://ably.com/docs/general/webhooks/ifttt
---

# ably_rule_ifttt (Resource)

The `ably_rule_ifttt` resource allows you to create and manage an Ably integration rule for IFTTT. Read more at https://ably.com/docs/general/webhooks/ifttt


## Example Usage

```terraform
resource "ably_rule_ifttt" "rule0" {
  app_id = ably_app.app0.id
  status = "enabled"
  source = {
    channel_filter = "^my-channel.*",
    type           = "channel.message"
  }
  request_mode = "single"
  target = {
    webhook_key = "aaa",
    event_name  = "bbb"
  }
}
```

<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `app_id` (String) The Ably application ID.
- `source` (Attributes) object (rule_source) (see [below for nested schema](#nestedatt--source))
- `target` (Attributes) object (rule_source) (see [below for nested schema](#nestedatt--target))

### Optional

- `request_mode` (String) This is Single Request mode or Batch Request mode. Single Request mode sends each event separately to the endpoint specified by the rule
- `status` (String) The status of the rule. Rules can be enabled or disabled.

### Read-Only

- `id` (String) The rule ID.

<a id="nestedatt--source"></a>
### Nested Schema for `source`

Required:

- `channel_filter` (String)
- `type` (String)


<a id="nestedatt--target"></a>
### Nested Schema for `target`

Required:

- `event_name` (String) The Event name is used to identify the IFTTT applet that will receive the Event, make sure the name matches the name of the IFTTT applet.
- `webhook_key` (String) The key in the Webhook Service Documentation page of your IFTTT account